In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
import wrappers
import test_utils

from test_utils import Tester, run_test_on_dataset
def make_plots(X, T, L, S, Ts, s_max=10):

    if S is not None:
        n = X.shape[1] + 1
    else:
        n = X.shape[1]
    
    plt.figure(figsize=(12, n*2.5+0.25))

    for i in range(X.shape[1]):
    
        plt.subplot(n, 1, i+1)
        ax = X[:, i]
        plt.plot(T, ax, linewidth=2, label='Original signal', color='C0')
        for t in T[L == 1]:
            plt.plot([t]*2, [ax.min(), ax.max()], color='0', linestyle='--')
        plt.ylim(ax.min(), ax.max())
        plt.xlim(0, T.max())
        plt.xticks(size=16)
        plt.yticks(size=16)
        if S is None:
            plt.xlabel("Time", size=16)
        #plt.legend(loc='upper left', fontsize=16)
        #plt.tight_layout()

    if S is not None:
        plt.subplot(n, 1, n)
        plt.plot(Ts, S, linewidth=3, label="Change-point score", color='C3')
        for t in T[L == 1]:
                plt.plot([t]*2, [-1, s_max], color='0', linestyle='--')
        plt.ylim(-1, s_max)
        plt.xlim(0, T.max())
        plt.xticks(size=16)
        plt.yticks(np.arange(0, s_max+1, 5), size=16)
        plt.xlabel("Time", size=16)
        plt.legend(loc='upper left', fontsize=16)
        #plt.tight_layout()

    #plt.show()

In [ ]:
%%time

dir_path = "../../datasets/Occupancy/"


models = [wrappers.OnlineCLF(lag_size=250, height=.1),
          wrappers.OnlineRuLSIF(lag_size=250, height=.1)]
          #wrappers.OrigRuLSIF(alpha=0.1, kernel_num=10, window_size=100, step=10, periods=1, height=0.1)]


for amodel in models:
    report = run_test_on_dataset(dir_path, amodel, downsample=1, margin=30, verbose=0, sigma=1.0,seed=12345)
    print(amodel)
    for rep in report:
        display(rep)

[  15  831 1455 2271 2895 3743 4271 5183 5759 6655 7215 8095]
[15, 831, 1455, 2271, 2895, 3743, 4271, 5183, 5759, 6655, 7215, 8095, 8143]
[15, 831, 1455, 2271, 2895, 3743, 4271, 5183, 5759, 6655, 7215, 8095, 8143] [253, 896, 1498, 2317, 2953, 3882, 4243, 5459, 6715, 7316, 8143]
[15, 831, 1455, 2271, 2895, 3743, 4271, 5183, 5759, 6655, 7215, 8095, 8143] [224, 886, 1486, 2292, 2917, 3863, 4217, 5565, 6716, 7295, 8143]
[15, 831, 1455, 2271, 2895, 3743, 4271, 5183, 5759, 6655, 7215, 8095, 8143] [221, 881, 1475, 2283, 2909, 3460, 3871, 4204, 5554, 6698, 7295, 8143]
[15, 831, 1455, 2271, 2895, 3743, 4271, 5183, 5759, 6655, 7215, 8095, 8143] [128, 882, 1470, 2290, 2904, 3426, 3875, 4212, 5492, 6681, 7279, 7870, 8143]
[15, 831, 1455, 2271, 2895, 3743, 4271, 5183, 5759, 6655, 7215, 8095, 8143] [250, 583, 1024, 4628, 6680, 6968, 8143]
[15, 831, 1455, 2271, 2895, 3743, 4271, 5183, 5759, 6655, 7215, 8095, 8143] [248, 877, 1501, 1909, 2271, 2388, 2616, 3053, 3561, 3858, 4440, 4801, 5422, 5787, 6711, 7771, 8143]
[15, 831, 1455, 2271, 2895, 3743, 4271, 5183, 5759, 6655, 7215, 8095, 8143] [239, 872, 1490, 1908, 2275, 2617, 2993, 3858, 4265, 4752, 5474, 6661, 7008, 7308, 8143]
[15, 831, 1455, 2271, 2895, 3743, 4271, 5183, 5759, 6655, 7215, 8095, 8143] [223, 871, 1493, 1856, 2281, 2617, 2954, 3856, 4253, 4825, 5205, 5660, 6054, 6673, 7309, 7860, 8143]
[15, 831, 1455, 2271, 2895, 3743, 4271, 5183, 5759, 6655, 7215, 8095, 8143] [259, 894, 1498, 2317, 2940, 3872, 4225, 5544, 6714, 7315, 8143]
[15, 831, 1455, 2271, 2895, 3743, 4271, 5183, 5759, 6655, 7215, 8095, 8143] [240, 888, 1481, 2291, 2909, 3353, 3870, 4210, 5572, 5991, 6305, 6696, 7291, 8143]
[15, 831, 1455, 2271, 2895, 3743, 4271, 5183, 5759, 6655, 7215, 8095, 8143] [253, 892, 1476, 2286, 2911, 3439, 3866, 4206, 4913, 5477, 6084, 6698, 7286, 8143]
[15, 831, 1455, 2271, 2895, 3743, 4271, 5183, 5759, 6655, 7215, 8095, 8143] [228, 890, 1469, 2285, 2904, 3451, 3863, 4201, 4913, 5567, 6684, 7259, 8143]
[15, 831, 1455, 2271, 2895, 3743, 4271, 5183, 5759, 6655, 7215, 8095, 8143] [308, 589, 895, 1614, 2470, 3096, 4713, 6985, 7515, 8143]
[15, 831, 1455, 2271, 2895, 3743, 4271, 5183, 5759, 6655, 7215, 8095, 8143] [244, 899, 1519, 2307, 2987, 3870, 4367, 5439, 6802, 6980, 7401, 8143]
[15, 831, 1455, 2271, 2895, 3743, 4271, 5183, 5759, 6655, 7215, 8095, 8143] [255, 889, 1495, 2305, 2946, 3874, 4233, 5462, 6713, 7309, 8143]
[15, 831, 1455, 2271, 2895, 3743, 4271, 5183, 5759, 6655, 7215, 8095, 8143] [241, 896, 1478, 2294, 2911, 3420, 3879, 4216, 4924, 5500, 6146, 6707, 7287, 8143]
[228, 890, 1469, 2285, 2904, 3451, 3863, 4201, 4913, 5567, 6684, 7259, 8143]
<wrappers.OnlineCLF object at 0x77eee97b6e70>

                    0   1           2           3
F1           0.384615 NaN    0.384615    0.384615
AUC          0.384615 NaN    0.384615    0.384615
FP           8.000000 NaN    8.000000    8.000000
DD         102.000000 NaN  102.000000  102.000000
Threshold   30.000000 NaN   30.000000   30.000000
Covering     0.768122 NaN    0.768122    0.768122
Runtime     28.363734 NaN   28.363734   28.363734

[  15  831 1455 2271 2895 3743 4271 5183 5759 6655 7215 8095]
[15, 831, 1455, 2271, 2895, 3743, 4271, 5183, 5759, 6655, 7215, 8095, 8143]
[223, 880, 1474, 2285, 2906, 3864, 4198, 5095, 5449, 6034, 6694, 7279, 8143]
<wrappers.OnlineRuLSIF object at 0x77eee97b6d80>

                   0   1          2          3
F1          0.307692 NaN   0.307692   0.307692
AUC         0.307692 NaN   0.307692   0.307692
FP          9.000000 NaN   9.000000   9.000000
DD         94.384615 NaN  94.384615  94.384615
Threshold  30.000000 NaN  30.000000  30.000000
Covering    0.787775 NaN   0.787775   0.787775
Runtime    73.749415 NaN  73.749415  73.749415

CPU times: user 316 ms, sys: 94.5 ms, total: 410 ms
Wall time: 1min 42s

In [ ]:
%%time

dir_path = "../../datasets/Occupancy/"


models = [wrappers.OrigRuLSIF(alpha=0.1, kernel_num=10, window_size=250, step=10, periods=1, height=0.1)]


for amodel in models:
    report = run_test_on_dataset(dir_path, amodel, downsample=1, margin=30, verbose=0, sigma=1.0,seed=12345)
    print(amodel)
    for rep in report:
        display(rep)

[  15  831 1455 2271 2895 3743 4271 5183 5759 6655 7215 8095]
[15, 831, 1455, 2271, 2895, 3743, 4271, 5183, 5759, 6655, 7215, 8095, 8143]
[270, 867, 1457, 2260, 2900, 3837, 4157, 5367, 5687, 6677, 6980, 7287, 8143]
<wrappers.OrigRuLSIF object at 0x77eee8a60ad0>

                   0   1          2          3
F1          0.384615 NaN   0.384615   0.384615
AUC         0.384615 NaN   0.384615   0.384615
FP          8.000000 NaN   8.000000   8.000000
DD         84.769231 NaN  84.769231  84.769231
Threshold  30.000000 NaN  30.000000  30.000000
Covering    0.798814 NaN   0.798814   0.798814
Runtime    12.170111 NaN  12.170111  12.170111

CPU times: user 832 ms, sys: 91 ms, total: 923 ms
Wall time: 12.2 s

In [ ]:
import zipfile
import json

zip_file_path = '../../datasets/MNISTSeq.zip'

with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_contents = zip_ref.namelist()
    json_file_name = zip_contents[0]
    with zip_ref.open(json_file_name) as json_file:
        data = json.load(json_file)

In [11]:
for sample in data.keys():
    df =pd.DataFrame(data[str(sample)]['data'],columns=['X'+str(i) for i in range(1,785)])
    df.insert(0,'Time',np.arange(df.shape[0]))
    df.to_csv(f'../data/MNIST_SWCPD/sample{sample}.csv',index=False)
    np.save(f"../data/MNIST_SWCPD/sample{sample}.npy",np.array(data[str(sample)]['target']))

In [5]:
%%time

dir_path = "../data/MNIST_SWCPD/"


models = [wrappers.OnlineCLF(lag_size=100, height=.1),
          wrappers.OnlineRuLSIF(lag_size=100, height=.1)]
          #wrappers.OrigRuLSIF(alpha=0.1, kernel_num=10, window_size=100, step=10, periods=1, height=0.1)]


for amodel in models:
    report = run_test_on_dataset(dir_path, amodel, downsample=1, margin=20, verbose=0, sigma=5.0,seed=12345)
    print(amodel)
    for rep in report:
        display(rep)

[200 400]
[200, 400, 600]
[200, 400, 600] [211, 363, 600]
[200, 400, 600] [198, 397, 600]
[200, 400, 600] [203, 443, 600]
[200, 400, 600] [203, 345, 396, 600]
[200, 400, 600] [600]
[200, 400, 600] [600]
[200, 400, 600] [293, 423, 600]
[200, 400, 600] [93, 162, 243, 380, 600]
[200, 400, 600] [224, 395, 600]
[200, 400, 600] [208, 448, 600]
[200, 400, 600] [220, 600]
[200, 400, 600] [223, 406, 600]
[200, 400, 600] [600]
[200, 400, 600] [96, 600]
[200, 400, 600] [216, 420, 600]
[200, 400, 600] [255, 392, 600]
[198, 397, 600]
[200 400]
[200, 400, 600]
[200, 400, 600] [215, 356, 600]
[200, 400, 600] [260, 486, 600]
[200, 400, 600] [236, 364, 600]
[200, 400, 600] [126, 320, 485, 600]
[200, 400, 600] [172, 600]
[200, 400, 600] [600]
[200, 400, 600] [88, 218, 393, 486, 600]
[200, 400, 600] [35, 181, 483, 600]
[200, 400, 600] [213, 385, 600]
[200, 400, 600] [220, 600]
[200, 400, 600] [231, 600]
[200, 400, 600] [197, 600]
[200, 400, 600] [600]
[200, 400, 600] [600]
[200, 400, 600] [86, 228, 600]
[200, 400, 600] [30, 223, 477, 600]
[213, 385, 600]
[200 400 600 800]
[200, 400, 600, 800, 1000]
[200, 400, 600, 800, 1000] [212, 389, 560, 833, 1000]
[200, 400, 600, 800, 1000] [209, 396, 577, 784, 871, 1000]
[200, 400, 600, 800, 1000] [205, 405, 600, 827, 1000]
[200, 400, 600, 800, 1000] [197, 251, 425, 609, 792, 881, 1000]
[200, 400, 600, 800, 1000] [529, 583, 1000]
[200, 400, 600, 800, 1000] [238, 590, 767, 854, 1000]
[200, 400, 600, 800, 1000] [455, 531, 730, 1000]
[200, 400, 600, 800, 1000] [273, 576, 769, 1000]
[200, 400, 600, 800, 1000] [211, 396, 592, 1000]
[200, 400, 600, 800, 1000] [60, 211, 391, 604, 797, 1000]
[200, 400, 600, 800, 1000] [208, 382, 623, 808, 1000]
[200, 400, 600, 800, 1000] [210, 435, 655, 740, 877, 1000]
[200, 400, 600, 800, 1000] [1000]
[200, 400, 600, 800, 1000] [81, 1000]
[200, 400, 600, 800, 1000] [79, 229, 394, 601, 1000]
[200, 400, 600, 800, 1000] [44, 268, 446, 607, 754, 1000]
[205, 405, 600, 827, 1000]
[200 400 600 800]
[200, 400, 600, 800, 1000]
[200, 400, 600, 800, 1000] [213, 379, 546, 666, 807, 1000]
[200, 400, 600, 800, 1000] [209, 409, 819, 1000]
[200, 400, 600, 800, 1000] [202, 360, 554, 793, 1000]
[200, 400, 600, 800, 1000] [288, 417, 591, 684, 863, 1000]
[200, 400, 600, 800, 1000] [450, 524, 583, 766, 1000]
[200, 400, 600, 800, 1000] [181, 765, 1000]
[200, 400, 600, 800, 1000] [87, 355, 538, 587, 768, 1000]
[200, 400, 600, 800, 1000] [543, 687, 1000]
[200, 400, 600, 800, 1000] [223, 398, 591, 805, 1000]
[200, 400, 600, 800, 1000] [220, 426, 609, 807, 1000]
[200, 400, 600, 800, 1000] [222, 426, 601, 797, 1000]
[200, 400, 600, 800, 1000] [177, 404, 587, 819, 1000]
[200, 400, 600, 800, 1000] [1000]
[200, 400, 600, 800, 1000] [1000]
[200, 400, 600, 800, 1000] [78, 225, 405, 589, 811, 1000]
[200, 400, 600, 800, 1000] [32, 225, 399, 551, 802, 846, 1000]
[223, 398, 591, 805, 1000]
[200 400 600 800]
[200, 400, 600, 800, 1000]
[200, 400, 600, 800, 1000] [214, 375, 546, 679, 832, 1000]
[200, 400, 600, 800, 1000] [208, 430, 553, 784, 1000]
[200, 400, 600, 800, 1000] [203, 400, 616, 798, 1000]
[200, 400, 600, 800, 1000] [233, 320, 568, 852, 1000]
[200, 400, 600, 800, 1000] [174, 528, 590, 735, 1000]
[200, 400, 600, 800, 1000] [688, 739, 1000]
[200, 400, 600, 800, 1000] [394, 524, 784, 1000]
[200, 400, 600, 800, 1000] [355, 587, 766, 827, 1000]
[200, 400, 600, 800, 1000] [233, 405, 801, 1000]
[200, 400, 600, 800, 1000] [220, 402, 592, 815, 1000]
[200, 400, 600, 800, 1000] [209, 399, 638, 845, 1000]
[200, 400, 600, 800, 1000] [210, 406, 612, 834, 1000]
[200, 400, 600, 800, 1000] [1000]
[200, 400, 600, 800, 1000] [79, 1000]
[200, 400, 600, 800, 1000] [98, 233, 400, 598, 1000]
[200, 400, 600, 800, 1000] [44, 202, 390, 642, 812, 1000]
[203, 400, 616, 798, 1000]
[200 400 600 800]
[200, 400, 600, 800, 1000]
[200, 400, 600, 800, 1000] [213, 381, 572, 793, 1000]
[200, 400, 600, 800, 1000] [259, 399, 606, 788, 1000]
[200, 400, 600, 800, 1000] [203, 389, 599, 814, 1000]
[200, 400, 600, 800, 1000] [187, 453, 561, 712, 866, 1000]
[200, 400, 600, 800, 1000] [171, 531, 588, 733, 1000]
[200, 400, 600, 800, 1000] [543, 737, 1000]
[200, 400, 600, 800, 1000] [395, 538, 735, 1000]
[200, 400, 600, 800, 1000] [259, 473, 639, 797, 1000]
[200, 400, 600, 800, 1000] [232, 398, 601, 1000]
[200, 400, 600, 800, 1000] [209, 373, 594, 843, 1000]
[200, 400, 600, 800, 1000] [220, 395, 602, 793, 1000]
[200, 400, 600, 800, 1000] [188, 405, 606, 877, 1000]
[200, 400, 600, 800, 1000] [1000]
[200, 400, 600, 800, 1000] [80, 585, 1000]
[200, 400, 600, 800, 1000] [98, 233, 402, 595, 1000]
[200, 400, 600, 800, 1000] [39, 209, 408, 588, 809, 1000]
[203, 389, 599, 814, 1000]
[200 400 600 800]
[200, 400, 600, 800, 1000]
[200, 400, 600, 800, 1000] [210, 400, 557, 771, 1000]
[200, 400, 600, 800, 1000] [207, 461, 539, 742, 1000]
[200, 400, 600, 800, 1000] [201, 402, 600, 837, 1000]
[200, 400, 600, 800, 1000] [206, 404, 528, 736, 825, 1000]
[200, 400, 600, 800, 1000] [168, 524, 583, 762, 1000]
[200, 400, 600, 800, 1000] [97, 163, 603, 678, 751, 1000]
[200, 400, 600, 800, 1000] [395, 586, 773, 1000]
[200, 400, 600, 800, 1000] [60, 220, 304, 359, 543, 769, 1000]
[200, 400, 600, 800, 1000] [220, 396, 592, 810, 1000]
[200, 400, 600, 800, 1000] [214, 417, 589, 754, 817, 1000]
[200, 400, 600, 800, 1000] [203, 376, 590, 811, 1000]
[200, 400, 600, 800, 1000] [200, 372, 433, 591, 806, 1000]
[200, 400, 600, 800, 1000] [1000]
[200, 400, 600, 800, 1000] [277, 542, 824, 1000]
[200, 400, 600, 800, 1000] [96, 230, 414, 591, 1000]
[200, 400, 600, 800, 1000] [207, 420, 571, 745, 814, 1000]
[201, 402, 600, 837, 1000]
[200 400]
[200, 400, 600]
[200, 400, 600] [213, 402, 600]
[200, 400, 600] [199, 425, 600]
[200, 400, 600] [209, 426, 600]
[200, 400, 600] [303, 448, 600]
[200, 400, 600] [600]
[200, 400, 600] [95, 163, 249, 600]
[200, 400, 600] [351, 470, 600]
[200, 400, 600] [95, 246, 411, 600]
[200, 400, 600] [224, 398, 600]
[200, 400, 600] [77, 224, 426, 600]
[200, 400, 600] [214, 422, 600]
[200, 400, 600] [212, 427, 600]
[200, 400, 600] [600]
[200, 400, 600] [89, 600]
[200, 400, 600] [94, 232, 417, 600]
[200, 400, 600] [213, 441, 600]
[213, 402, 600]
[200 400]
[200, 400, 600]
[200, 400, 600] [214, 386, 600]
[200, 400, 600] [266, 320, 394, 600]
[200, 400, 600] [203, 386, 600]
[200, 400, 600] [229, 600]
[200, 400, 600] [174, 600]
[200, 400, 600] [97, 486, 600]
[200, 400, 600] [87, 217, 397, 485, 600]
[200, 400, 600] [92, 176, 391, 600]
[200, 400, 600] [210, 393, 600]
[200, 400, 600] [228, 412, 600]
[200, 400, 600] [220, 419, 600]
[200, 400, 600] [202, 432, 600]
[200, 400, 600] [600]
[200, 400, 600] [600]
[200, 400, 600] [84, 229, 399, 600]
[200, 400, 600] [34, 228, 409, 600]
[203, 386, 600]
[200 400]
[200, 400, 600]
[200, 400, 600] [216, 363, 600]
[200, 400, 600] [244, 399, 600]
[200, 400, 600] [202, 405, 600]
[200, 400, 600] [278, 471, 600]
[200, 400, 600] [600]
[200, 400, 600] [340, 479, 600]
[200, 400, 600] [396, 471, 600]
[200, 400, 600] [331, 486, 600]
[200, 400, 600] [235, 400, 600]
[200, 400, 600] [216, 398, 600]
[200, 400, 600] [222, 406, 600]
[200, 400, 600] [204, 365, 600]
[200, 400, 600] [600]
[200, 400, 600] [79, 388, 600]
[200, 400, 600] [100, 237, 400, 600]
[200, 400, 600] [42, 233, 431, 600]
[202, 405, 600]
[200 400 600]
[200, 400, 600, 800]
[200, 400, 600, 800] [210, 386, 553, 800]
[200, 400, 600, 800] [214, 452, 584, 800]
[200, 400, 600, 800] [204, 411, 600, 800]
[200, 400, 600, 800] [209, 392, 458, 637, 800]
[200, 400, 600, 800] [526, 800]
[200, 400, 600, 800] [642, 800]
[200, 400, 600, 800] [291, 396, 530, 800]
[200, 400, 600, 800] [231, 413, 584, 800]
[200, 400, 600, 800] [225, 402, 601, 800]
[200, 400, 600, 800] [206, 435, 800]
[200, 400, 600, 800] [204, 428, 585, 800]
[200, 400, 600, 800] [209, 346, 593, 800]
[200, 400, 600, 800] [800]
[200, 400, 600, 800] [96, 330, 574, 800]
[200, 400, 600, 800] [219, 430, 800]
[200, 400, 600, 800] [28, 219, 426, 601, 800]
[204, 411, 600, 800]
[200 400 600]
[200, 400, 600, 800]
[200, 400, 600, 800] [213, 389, 554, 800]
[200, 400, 600, 800] [265, 391, 566, 800]
[200, 400, 600, 800] [201, 392, 597, 800]
[200, 400, 600, 800] [197, 399, 531, 574, 800]
[200, 400, 600, 800] [526, 800]
[200, 400, 600, 800] [246, 345, 428, 522, 679, 800]
[200, 400, 600, 800] [348, 525, 663, 800]
[200, 400, 600, 800] [34, 170, 238, 523, 610, 800]
[200, 400, 600, 800] [230, 396, 603, 800]
[200, 400, 600, 800] [206, 257, 422, 588, 800]
[200, 400, 600, 800] [200, 379, 605, 800]
[200, 400, 600, 800] [221, 363, 425, 607, 800]
[200, 400, 600, 800] [800]
[200, 400, 600, 800] [81, 800]
[200, 400, 600, 800] [79, 219, 401, 599, 800]
[200, 400, 600, 800] [215, 408, 552, 677, 800]
[201, 392, 597, 800]
[200 400 600]
[200, 400, 600, 800]
[200, 400, 600, 800] [212, 391, 539, 667, 800]
[200, 400, 600, 800] [206, 448, 800]
[200, 400, 600, 800] [206, 362, 555, 800]
[200, 400, 600, 800] [195, 399, 800]
[200, 400, 600, 800] [528, 800]
[200, 400, 600, 800] [33, 283, 519, 800]
[200, 400, 600, 800] [34, 298, 535, 800]
[200, 400, 600, 800] [27, 381, 519, 800]
[200, 400, 600, 800] [222, 398, 588, 800]
[200, 400, 600, 800] [220, 403, 469, 544, 800]
[200, 400, 600, 800] [199, 402, 603, 676, 800]
[200, 400, 600, 800] [220, 439, 590, 800]
[200, 400, 600, 800] [800]
[200, 400, 600, 800] [85, 320, 800]
[200, 400, 600, 800] [96, 229, 400, 590, 800]
[200, 400, 600, 800] [29, 258, 387, 595, 800]
[199, 402, 603, 676, 800]
[200 400 600]
[200, 400, 600, 800]
[200, 400, 600, 800] [210, 391, 546, 683, 800]
[200, 400, 600, 800] [177, 319, 411, 550, 800]
[200, 400, 600, 800] [199, 425, 615, 800]
[200, 400, 600, 800] [164, 401, 664, 800]
[200, 400, 600, 800] [528, 800]
[200, 400, 600, 800] [245, 343, 537, 673, 800]
[200, 400, 600, 800] [352, 521, 800]
[200, 400, 600, 800] [35, 229, 286, 555, 677, 800]
[200, 400, 600, 800] [230, 396, 588, 800]
[200, 400, 600, 800] [212, 407, 605, 800]
[200, 400, 600, 800] [209, 405, 627, 800]
[200, 400, 600, 800] [800]
[200, 400, 600, 800][200, 400, 600, 800]  [203, 449, 541, 800][86, 800]

[200, 400, 600, 800] [79, 218, 407, 575, 800]
[200, 400, 600, 800] [186, 442, 591, 800]
[212, 407, 605, 800]
[200 400 600]
[200, 400, 600, 800]
[200, 400, 600, 800] [213, 388, 546, 686, 800]
[200, 400, 600, 800] [259, 428, 602, 800]
[200, 400, 600, 800] [205, 373, 567, 800]
[200, 400, 600, 800] [207, 466, 624, 800]
[200, 400, 600, 800] [175, 525, 589, 800]
[200, 400, 600, 800] [103, 542, 615, 800]
[200, 400, 600, 800] [526, 582, 800]
[200, 400, 600, 800] [93, 462, 590, 644, 800]
[200, 400, 600, 800] [226, 394, 588, 800]
[200, 400, 600, 800] [216, 439, 588, 800]
[200, 400, 600, 800] [215, 449, 552, 800]
[200, 400, 600, 800] [265, 326, 603, 800]
[200, 400, 600, 800] [800]
[200, 400, 600, 800] [321, 800]
[200, 400, 600, 800] [85, 231, 413, 573, 800]
[200, 400, 600, 800] [35, 127, 216, 423, 572, 800]
[226, 394, 588, 800]
<wrappers.OnlineCLF object at 0x77eef877cd10>

                   0         1          2          3
F1          0.935926  0.097564   0.750000   1.000000
AUC         0.936667  0.097223   0.750000   1.000000
FP          0.333333  0.487950   0.000000   1.000000
DD          6.490000  3.784795   1.666667  16.400000
Threshold  20.000000  0.000000  20.000000  20.000000
Covering    0.941052  0.027837   0.893898   0.983490
Runtime     3.427849  0.765409   2.332376   4.297882

[200 400]
[200, 400, 600]
[204, 416, 600]
[200 400]
[200, 400, 600]
[210, 397, 600]
[200 400 600 800]
[200, 400, 600, 800, 1000]
[208, 408, 594, 802, 1000]
[200 400 600 800]
[200, 400, 600, 800, 1000]
[208, 412, 586, 794, 1000]
[200 400 600 800]
[200, 400, 600, 800, 1000]
[208, 429, 577, 803, 1000]
[200 400 600 800]
[200, 400, 600, 800, 1000]
[205, 368, 588, 803, 1000]
[200 400 600 800]
[200, 400, 600, 800, 1000]
[201, 401, 583, 788, 1000]
[200 400]
[200, 400, 600]
[218, 398, 600]
[200 400]
[200, 400, 600]
[206, 391, 600]
[200 400]
[200, 400, 600]
[208, 407, 600]
[200 400 600]
[200, 400, 600, 800]
[205, 393, 593, 800]
[200 400 600]
[200, 400, 600, 800]
[204, 399, 593, 800]
[200 400 600]
[200, 400, 600, 800]
[199, 424, 596, 800]
[200 400 600]
[200, 400, 600, 800]
[199, 390, 590, 800]
[200 400 600]
[200, 400, 600, 800]
[261, 428, 598, 800]
<wrappers.OnlineRuLSIF object at 0x77eee97b5d90>

                   0         1          2          3
F1          0.910000  0.167118   0.500000   1.000000
AUC         0.910000  0.167118   0.500000   1.000000
FP          0.400000  0.736788   0.000000   2.000000
DD          7.511111  4.877535   3.000000  22.750000
Threshold  20.000000  0.000000  20.000000  20.000000
Covering    0.929491  0.041308   0.804008   0.970444
Runtime     8.109012  2.078864   5.479291  11.301667

CPU times: user 2.31 s, sys: 557 ms, total: 2.86 s
Wall time: 2min 55s

In [13]:
%%time

dir_path = "../data/MNIST_SWCPD/"


models = [wrappers.OrigRuLSIF(alpha=0.1, kernel_num=10, window_size=100, step=10, periods=1, height=0.1)]


for amodel in models:
    report = run_test_on_dataset(dir_path, amodel, downsample=1, margin=20, verbose=0, sigma=5.0,seed=12345)
    print(amodel)
    for rep in report:
        display(rep)

[200 400]
[200, 400, 600]
[600]
[200 400]
[200, 400, 600]
[600]
[200 400 600 800]
[200, 400, 600, 800, 1000]
[1000]
[200 400 600 800]
[200, 400, 600, 800, 1000]
[1000]
[200 400 600 800]
[200, 400, 600, 800, 1000]
[1000]
[200 400 600 800]
[200, 400, 600, 800, 1000]
[1000]
[200 400 600 800]
[200, 400, 600, 800, 1000]
[1000]
[200 400]
[200, 400, 600]
[600]
[200 400]
[200, 400, 600]
[600]
[200 400]
[200, 400, 600]
[600]
[200 400 600]
[200, 400, 600, 800]
[800]
[200 400 600]
[200, 400, 600, 800]
[800]
[200 400 600]
[200, 400, 600, 800]
[800]
[200 400 600]
[200, 400, 600, 800]
[800]
[200 400 600]
[200, 400, 600, 800]
[800]
<wrappers.OrigRuLSIF object at 0x77eef4bfcaa0>

                   0         1          2          3
F1          0.411111  0.070897   0.333333   0.500000
AUC         0.630556  0.028464   0.600000   0.666667
FP          0.000000  0.000000   0.000000   0.000000
DD          0.000000  0.000000   0.000000   0.000000
Threshold  20.000000  0.000000  20.000000  20.000000
Covering    0.261111  0.056928   0.200000   0.333333
Runtime     0.606861  0.152665   0.396035   0.873684

CPU times: user 3.13 s, sys: 2.38 s, total: 5.51 s
Wall time: 10.6 s

In [ ]:


X_train = np.loadtxt("../../datasets/HAR_NEW/UCI HAR Dataset/train/X_train.txt"   
)
y_train = np.loadtxt("../../datasets/HAR_NEW/UCI HAR Dataset/train/y_train.txt")

human = np.loadtxt("../../datasets/HAR_NEW/UCI HAR Dataset/train/subject_train.txt")


X_test = np.loadtxt("../../datasets/HAR_NEW/UCI HAR Dataset/test/X_test.txt")

y_test = np.loadtxt("../../datasets/HAR_NEW/UCI HAR Dataset/test/y_test.txt")

human_test = np.loadtxt("../../datasets/HAR_NEW/UCI HAR Dataset/test/subject_test.txt")


df_train = pd.DataFrame(X_train)
df_train['state']  =y_train
df_train['human'] = human.astype(int)

df_test = pd.DataFrame(X_test)
df_test['state']  =y_test
df_test['human'] = human_test.astype(int)

for human in df_train['human'].unique():
    tmp = df_train[df_train['human']==human]
    tmp = tmp.reset_index(drop=True)
    
    GroundTruth = tmp.index[tmp.iloc[:,-2].diff()!=0][1:]+1

    data = tmp.iloc[:,:-2].values.astype(np.float32)
    data = (data-np.mean(data))/np.std(data)


    np.save(f'../data/HAR_NEW/{human}.npy',GroundTruth.values)




for human in df_test['human'].unique():
    tmp = df_test[df_test['human']==human]
    tmp = tmp.reset_index(drop=True)
    
    GroundTruth = tmp.index[tmp.iloc[:,-2].diff()!=0][1:]+1

    data = tmp.iloc[:,:-2].values.astype(np.float32)
    data = (data-np.mean(data))/np.std(data)


    #np.savetxt(f'data{human}.csv',data,delimiter=",")
    np.save(f'../data/HAR_NEW/{human}.npy',GroundTruth.values)

In [ ]:
%%time


dir_path = "../data/HAR_NEW/"




models = [wrappers.OnlineCLF(lag_size=20, height=.1),
          wrappers.OnlineRuLSIF(lag_size=20, height=.1)]
          #wrappers.OrigRuLSIF(alpha=0.1, kernel_num=10, window_size=100, step=10, periods=1, height=0.1)]


for amodel in models:
    report = run_test_on_dataset(dir_path, amodel, downsample=1, margin=10, verbose=0, sigma=1.0,seed=12345)
    print(amodel)
    for rep in report:
        display(rep)

[ 28  52  79 126 151 177 203 214 226 238 249 297 304 331]
[28, 52, 79, 126, 151, 177, 203, 214, 226, 238, 249, 297, 304, 331, 347]
[28, 52, 79, 126, 151, 177, 203, 214, 226, 238, 249, 297, 304, 331, 347] [78, 176, 250, 347]
[28, 52, 79, 126, 151, 177, 203, 214, 226, 238, 249, 297, 304, 331, 347] [5, 23, 40, 78, 175, 209, 249, 305, 347]
[28, 52, 79, 126, 151, 177, 203, 214, 226, 238, 249, 297, 304, 331, 347] [17, 79, 125, 151, 176, 202, 248, 301, 347]
[28, 52, 79, 126, 151, 177, 203, 214, 226, 238, 249, 297, 304, 331, 347] [17, 63, 89, 135, 175, 204, 248, 301, 347]
[28, 52, 79, 126, 151, 177, 203, 214, 226, 238, 249, 297, 304, 331, 347] [70, 90, 347]
[28, 52, 79, 126, 151, 177, 203, 214, 226, 238, 249, 297, 304, 331, 347] [29, 117, 321, 347]
[28, 52, 79, 126, 151, 177, 203, 214, 226, 238, 249, 297, 304, 331, 347] [81, 100, 138, 200, 347]
[28, 52, 79, 126, 151, 177, 203, 214, 226, 238, 249, 297, 304, 331, 347] [30, 62, 92, 118, 151, 179, 251, 347]
[28, 52, 79, 126, 151, 177, 203, 214, 226, 238, 249, 297, 304, 331, 347] [27, 77, 174, 261, 347]
[28, 52, 79, 126, 151, 177, 203, 214, 226, 238, 249, 297, 304, 331, 347] [28, 77, 173, 257, 300, 347]
[28, 52, 79, 126, 151, 177, 203, 214, 226, 238, 249, 297, 304, 331, 347] [42, 78, 164, 247, 299, 347]
[28, 52, 79, 126, 151, 177, 203, 214, 226, 238, 249, 297, 304, 331, 347] [77, 162, 245, 299, 347]
[28, 52, 79, 126, 151, 177, 203, 214, 226, 238, 249, 297, 304, 331, 347] [77, 247, 347]
[28, 52, 79, 126, 151, 177, 203, 214, 226, 238, 249, 297, 304, 331, 347] [27, 71, 299, 347]
[28, 52, 79, 126, 151, 177, 203, 214, 226, 238, 249, 297, 304, 331, 347] [28, 79, 119, 177, 267, 307, 347]
[28, 52, 79, 126, 151, 177, 203, 214, 226, 238, 249, 297, 304, 331, 347] [30, 79, 161, 257, 309, 347]
[17, 79, 125, 151, 176, 202, 248, 301, 347]
[ 24  48  79 106 125 148 169 199 226 252 271]
[24, 48, 79, 106, 125, 148, 169, 199, 226, 252, 271, 294]
[24, 48, 79, 106, 125, 148, 169, 199, 226, 252, 271, 294] [18, 77, 89, 147, 250, 294]
[24, 48, 79, 106, 125, 148, 169, 199, 226, 252, 271, 294] [18, 84, 147, 238, 294]
[24, 48, 79, 106, 125, 148, 169, 199, 226, 252, 271, 294] [19, 50, 77, 102, 145, 198, 226, 270, 294]
[24, 48, 79, 106, 125, 148, 169, 199, 226, 252, 271, 294] [22, 58, 85, 103, 145, 195, 226, 294]
[24, 48, 79, 106, 125, 148, 169, 199, 226, 252, 271, 294] [98, 294]
[24, 48, 79, 106, 125, 148, 169, 199, 226, 252, 271, 294] [19, 294]
[24, 48, 79, 106, 125, 148, 169, 199, 226, 252, 271, 294] [23, 82, 183, 260, 294]
[24, 48, 79, 106, 125, 148, 169, 199, 226, 252, 271, 294] [10, 71, 151, 193, 232, 294]
[24, 48, 79, 106, 125, 148, 169, 199, 226, 252, 271, 294] [23, 96, 147, 239, 294]
[24, 48, 79, 106, 125, 148, 169, 199, 226, 252, 271, 294] [22, 76, 146, 236, 294]
[24, 48, 79, 106, 125, 148, 169, 199, 226, 252, 271, 294] [28, 78, 144, 235, 294]
[24, 48, 79, 106, 125, 148, 169, 199, 226, 252, 271, 294] [76, 143, 236, 294]
[24, 48, 79, 106, 125, 148, 169, 199, 226, 252, 271, 294] [98, 227, 294]
[24, 48, 79, 106, 125, 148, 169, 199, 226, 252, 271, 294] [26, 89, 294]
[24, 48, 79, 106, 125, 148, 169, 199, 226, 252, 271, 294] [26, 97, 150, 239, 294]
[24, 48, 79, 106, 125, 148, 169, 199, 226, 252, 271, 294] [26, 79, 148, 188, 237, 294]
[19, 50, 77, 102, 145, 198, 226, 270, 294]
[ 22  48  78 107 129 155 181 208 235 265 289]
[22, 48, 78, 107, 129, 155, 181, 208, 235, 265, 289, 316]
[22, 48, 78, 107, 129, 155, 181, 208, 235, 265, 289, 316] [18, 104, 154, 179, 263, 316]
[22, 48, 78, 107, 129, 155, 181, 208, 235, 265, 289, 316] [17, 52, 83, 104, 154, 181, 241, 264, 292, 316]
[22, 48, 78, 107, 129, 155, 181, 208, 235, 265, 289, 316] [19, 50, 104, 154, 180, 235, 264, 291, 316]
[22, 48, 78, 107, 129, 155, 181, 208, 235, 265, 289, 316] [19, 52, 78, 130, 154, 235, 264, 316]
[22, 48, 78, 107, 129, 155, 181, 208, 235, 265, 289, 316] [71, 100, 170, 280, 316]
[22, 48, 78, 107, 129, 155, 181, 208, 235, 265, 289, 316] [82, 172, 316]
[22, 48, 78, 107, 129, 155, 181, 208, 235, 265, 289, 316] [80, 100, 260, 289, 316]
[22, 48, 78, 107, 129, 155, 181, 208, 235, 265, 289, 316] [39, 81, 99, 129, 162, 187, 252, 290, 316]
[22, 48, 78, 107, 129, 155, 181, 208, 235, 265, 289, 316] [27, 97, 159, 255, 316]
[22, 48, 78, 107, 129, 155, 181, 208, 235, 265, 289, 316] [19, 85, 151, 248, 316]
[22, 48, 78, 107, 129, 155, 181, 208, 235, 265, 289, 316] [39, 94, 121, 150, 232, 316]
[22, 48, 78, 107, 129, 155, 181, 208, 235, 265, 289, 316] [39, 86, 121, 150, 248, 282, 316]
[22, 48, 78, 107, 129, 155, 181, 208, 235, 265, 289, 316] [97, 190, 230, 316]
[22, 48, 78, 107, 129, 155, 181, 208, 235, 265, 289, 316] [97, 259, 316]
[22, 48, 78, 107, 129, 155, 181, 208, 235, 265, 289, 316] [20, 99, 156, 249, 316]
[22, 48, 78, 107, 129, 155, 181, 208, 235, 265, 289, 316] [19, 88, 118, 150, 247, 316]
[19, 50, 104, 154, 180, 235, 264, 291, 316]
[ 28  56  83 110 135 162 196 219 252 275 296]
[28, 56, 83, 110, 135, 162, 196, 219, 252, 275, 296, 320]
[28, 56, 83, 110, 135, 162, 196, 219, 252, 275, 296, 320] [19, 94, 161, 256, 268, 320]
[28, 56, 83, 110, 135, 162, 196, 219, 252, 275, 296, 320] [19, 50, 86, 110, 161, 224, 252, 296, 320]
[28, 56, 83, 110, 135, 162, 196, 219, 252, 275, 296, 320] [19, 50, 82, 109, 164, 219, 256, 267, 320]
[28, 56, 83, 110, 135, 162, 196, 219, 252, 275, 296, 320] [19, 80, 164, 218, 257, 320]
[28, 56, 83, 110, 135, 162, 196, 219, 252, 275, 296, 320] [91, 181, 320]
[28, 56, 83, 110, 135, 162, 196, 219, 252, 275, 296, 320] [80, 120, 180, 289, 320]
[28, 56, 83, 110, 135, 162, 196, 219, 252, 275, 296, 320] [91, 172, 209, 259, 320]
[28, 56, 83, 110, 135, 162, 196, 219, 252, 275, 296, 320] [32, 90, 138, 171, 259, 286, 320]
[28, 56, 83, 110, 135, 162, 196, 219, 252, 275, 296, 320] [27, 93, 160, 262, 320]
[28, 56, 83, 110, 135, 162, 196, 219, 252, 275, 296, 320] [27, 44, 82, 159, 217, 261, 320]
[28, 56, 83, 110, 135, 162, 196, 219, 252, 275, 296, 320] [80, 159, 205, 260, 320]
[28, 56, 83, 110, 135, 162, 196, 219, 252, 275, 296, 320] [51, 81, 159, 222, 260, 320]
[28, 56, 83, 110, 135, 162, 196, 219, 252, 275, 296, 320] [89, 208, 249, 320]
[28, 56, 83, 110, 135, 162, 196, 219, 252, 275, 296, 320] [87, 168, 320]
[28, 56, 83, 110, 135, 162, 196, 219, 252, 275, 296, 320] [26, 88, 159, 260, 320]
[28, 56, 83, 110, 135, 162, 196, 219, 252, 275, 296, 320] [29, 88, 160, 260, 320]
[19, 50, 86, 110, 161, 224, 252, 296, 320]
[ 28  52  85 115 142 173 203 228 257 284 304]
[28, 52, 85, 115, 142, 173, 203, 228, 257, 284, 304, 327]
[28, 52, 85, 115, 142, 173, 203, 228, 257, 284, 304, 327] [18, 85, 117, 172, 259, 327]
[28, 52, 85, 115, 142, 173, 203, 228, 257, 284, 304, 327] [20, 51, 84, 120, 140, 175, 228, 258, 303, 327]
[28, 52, 85, 115, 142, 173, 203, 228, 257, 284, 304, 327] [20, 53, 84, 113, 143, 174, 227, 256, 280, 303, 327]
[28, 52, 85, 115, 142, 173, 203, 228, 257, 284, 304, 327] [26, 57, 84, 114, 144, 178, 231, 257, 303, 327]
[28, 52, 85, 115, 142, 173, 203, 228, 257, 284, 304, 327] [100, 327]
[28, 52, 85, 115, 142, 173, 203, 228, 257, 284, 304, 327] [83, 229, 281, 327]
[28, 52, 85, 115, 142, 173, 203, 228, 257, 284, 304, 327] [28, 92, 147, 183, 209, 261, 327]
[28, 52, 85, 115, 142, 173, 203, 228, 257, 284, 304, 327] [29, 79, 110, 127, 191, 261, 280, 327]
[28, 52, 85, 115, 142, 173, 203, 228, 257, 284, 304, 327] [20, 97, 177, 270, 327]
[28, 52, 85, 115, 142, 173, 203, 228, 257, 284, 304, 327] [19, 83, 175, 224, 264, 327]
[28, 52, 85, 115, 142, 173, 203, 228, 257, 284, 304, 327] [47, 85, 138, 177, 260, 327]
[28, 52, 85, 115, 142, 173, 203, 228, 257, 284, 304, 327] [84, 177, 261, 327]
[28, 52, 85, 115, 142, 173, 203, 228, 257, 284, 304, 327] [327]
[28, 52, 85, 115, 142, 173, 203, 228, 257, 284, 304, 327] [18, 90, 327]
[28, 52, 85, 115, 142, 173, 203, 228, 257, 284, 304, 327] [18, 106, 178, 268, 327]
[28, 52, 85, 115, 142, 173, 203, 228, 257, 284, 304, 327] [19, 80, 179, 260, 327]
[20, 53, 84, 113, 143, 174, 227, 256, 280, 303, 327]
[ 31  57  82 112 136 163 193 221 247 276 297]
[31, 57, 82, 112, 136, 163, 193, 221, 247, 276, 297, 323]
[31, 57, 82, 112, 136, 163, 193, 221, 247, 276, 297, 323] [17, 56, 110, 167, 275, 323]
[31, 57, 82, 112, 136, 163, 193, 221, 247, 276, 297, 323] [21, 37, 82, 110, 162, 193, 274, 323]
[31, 57, 82, 112, 136, 163, 193, 221, 247, 276, 297, 323] [18, 52, 84, 110, 137, 165, 219, 274, 323]
[31, 57, 82, 112, 136, 163, 193, 221, 247, 276, 297, 323] [17, 81, 110, 137, 162, 246, 273, 323]
[31, 57, 82, 112, 136, 163, 193, 221, 247, 276, 297, 323] [107, 241, 323]
[31, 57, 82, 112, 136, 163, 193, 221, 247, 276, 297, 323] [29, 83, 109, 217, 281, 323]
[31, 57, 82, 112, 136, 163, 193, 221, 247, 276, 297, 323] [29, 82, 107, 323]
[31, 57, 82, 112, 136, 163, 193, 221, 247, 276, 297, 323] [21, 77, 109, 171, 251, 323]
[31, 57, 82, 112, 136, 163, 193, 221, 247, 276, 297, 323] [27, 108, 181, 265, 323]
[31, 57, 82, 112, 136, 163, 193, 221, 247, 276, 297, 323] [20, 92, 172, 203, 263, 323]
[31, 57, 82, 112, 136, 163, 193, 221, 247, 276, 297, 323] [100, 128, 158, 262, 281, 323]
[31, 57, 82, 112, 136, 163, 193, 221, 247, 276, 297, 323] [92, 128, 158, 262, 323]
[31, 57, 82, 112, 136, 163, 193, 221, 247, 276, 297, 323] [108, 266, 323]
[31, 57, 82, 112, 136, 163, 193, 221, 247, 276, 297, 323] [100, 269, 323]
[31, 57, 82, 112, 136, 163, 193, 221, 247, 276, 297, 323] [20, 108, 170, 268, 323]
[31, 57, 82, 112, 136, 163, 193, 221, 247, 276, 297, 323] [20, 80, 167, 216, 261, 323]
[18, 52, 84, 110, 137, 165, 219, 274, 323]
[ 28  55  89 117 138 162 188 220 258 284 305]
[28, 55, 89, 117, 138, 162, 188, 220, 258, 284, 305, 328]
[28, 55, 89, 117, 138, 162, 188, 220, 258, 284, 305, 328] [89, 114, 162, 281, 328]
[28, 55, 89, 117, 138, 162, 188, 220, 258, 284, 305, 328] [22, 52, 88, 115, 162, 192, 267, 328]
[28, 55, 89, 117, 138, 162, 188, 220, 258, 284, 305, 328] [18, 50, 88, 114, 162, 260, 281, 328]
[28, 55, 89, 117, 138, 162, 188, 220, 258, 284, 305, 328] [25, 52, 96, 115, 132, 162, 226, 281, 328]
[28, 55, 89, 117, 138, 162, 188, 220, 258, 284, 305, 328] [328]
[28, 55, 89, 117, 138, 162, 188, 220, 258, 284, 305, 328] [73, 109, 153, 218, 300, 328]
[28, 55, 89, 117, 138, 162, 188, 220, 258, 284, 305, 328] [29, 80, 172, 227, 328]
[28, 55, 89, 117, 138, 162, 188, 220, 258, 284, 305, 328] [80, 108, 161, 228, 263, 291, 328]
[28, 55, 89, 117, 138, 162, 188, 220, 258, 284, 305, 328] [29, 105, 161, 273, 328]
[28, 55, 89, 117, 138, 162, 188, 220, 258, 284, 305, 328] [28, 103, 159, 271, 328]
[28, 55, 89, 117, 138, 162, 188, 220, 258, 284, 305, 328] [46, 103, 131, 158, 222, 273, 328]
[28, 55, 89, 117, 138, 162, 188, 220, 258, 284, 305, 328] [91, 157, 270, 328]
[28, 55, 89, 117, 138, 162, 188, 220, 258, 284, 305, 328] [108, 260, 328]
[28, 55, 89, 117, 138, 162, 188, 220, 258, 284, 305, 328] [20, 89, 288, 328]
[28, 55, 89, 117, 138, 162, 188, 220, 258, 284, 305, 328] [26, 106, 161, 277, 328]
[28, 55, 89, 117, 138, 162, 188, 220, 258, 284, 305, 328] [20, 89, 160, 209, 269, 328]
[25, 52, 96, 115, 132, 162, 226, 281, 328]
[ 37  68 103 129 153 180 222 260 295 320 343]
[37, 68, 103, 129, 153, 180, 222, 260, 295, 320, 343, 366]
[37, 68, 103, 129, 153, 180, 222, 260, 295, 320, 343, 366] [18, 68, 128, 180, 318, 366]
[37, 68, 103, 129, 153, 180, 222, 260, 295, 320, 343, 366] [18, 49, 105, 129, 178, 306, 318, 366]
[37, 68, 103, 129, 153, 180, 222, 260, 295, 320, 343, 366] [18, 42, 68, 102, 129, 179, 219, 259, 318, 366]
[37, 68, 103, 129, 153, 180, 222, 260, 295, 320, 343, 366] [60, 102, 130, 179, 218, 259, 306, 318, 366]
[37, 68, 103, 129, 153, 180, 222, 260, 295, 320, 343, 366] [100, 366]
[37, 68, 103, 129, 153, 180, 222, 260, 295, 320, 343, 366] [11, 170, 223, 281, 366]
[37, 68, 103, 129, 153, 180, 222, 260, 295, 320, 343, 366] [10, 109, 147, 239, 282, 366]
[37, 68, 103, 129, 153, 180, 222, 260, 295, 320, 343, 366] [19, 79, 117, 182, 221, 271, 299, 366]
[37, 68, 103, 129, 153, 180, 222, 260, 295, 320, 343, 366] [16, 120, 188, 310, 366]
[37, 68, 103, 129, 153, 180, 222, 260, 295, 320, 343, 366] [15, 67, 117, 140, 176, 220, 308, 366]
[37, 68, 103, 129, 153, 180, 222, 260, 295, 320, 343, 366] [17, 118, 141, 173, 300, 329, 366]
[37, 68, 103, 129, 153, 180, 222, 260, 295, 320, 343, 366] [63, 118, 140, 175, 221, 309, 330, 366]
[37, 68, 103, 129, 153, 180, 222, 260, 295, 320, 343, 366] [118, 259, 319, 366]
[37, 68, 103, 129, 153, 180, 222, 260, 295, 320, 343, 366] [19, 118, 366]
[37, 68, 103, 129, 153, 180, 222, 260, 295, 320, 343, 366] [18, 117, 180, 310, 366]
[37, 68, 103, 129, 153, 180, 222, 260, 295, 320, 343, 366] [20, 38, 68, 110, 176, 220, 307, 366]
[18, 42, 68, 102, 129, 179, 219, 259, 318, 366]
[ 44  77 112 144 152 160 168 176 183 191 226 257 293 322 337 361]
[44, 77, 112, 144, 152, 160, 168, 176, 183, 191, 226, 257, 293, 322, 337, 361, 368]
[44, 77, 112, 144, 152, 160, 168, 176, 183, 191, 226, 257, 293, 322, 337, 361, 368] [6, 113, 148, 198, 315, 368]
[44, 77, 112, 144, 152, 160, 168, 176, 183, 191, 226, 257, 293, 322, 337, 361, 368] [18, 111, 147, 196, 260, 292, 319, 368]
[44, 77, 112, 144, 152, 160, 168, 176, 183, 191, 226, 257, 293, 322, 337, 361, 368] [18, 49, 81, 111, 147, 194, 260, 298, 320, 368]
[44, 77, 112, 144, 152, 160, 168, 176, 183, 191, 226, 257, 293, 322, 337, 361, 368] [8, 42, 62, 75, 110, 147, 193, 266, 294, 368]
[44, 77, 112, 144, 152, 160, 168, 176, 183, 191, 226, 257, 293, 322, 337, 361, 368] [368]
[44, 77, 112, 144, 152, 160, 168, 176, 183, 191, 226, 257, 293, 322, 337, 361, 368] [63, 111, 368]
[44, 77, 112, 144, 152, 160, 168, 176, 183, 191, 226, 257, 293, 322, 337, 361, 368] [29, 81, 110, 319, 368]
[44, 77, 112, 144, 152, 160, 168, 176, 183, 191, 226, 257, 293, 322, 337, 361, 368] [29, 80, 109, 191, 319, 368]
[44, 77, 112, 144, 152, 160, 168, 176, 183, 191, 226, 257, 293, 322, 337, 361, 368] [111, 149, 209, 259, 307, 368]
[44, 77, 112, 144, 152, 160, 168, 176, 183, 191, 226, 257, 293, 322, 337, 361, 368] [53, 75, 117, 197, 301, 368]
[44, 77, 112, 144, 152, 160, 168, 176, 183, 191, 226, 257, 293, 322, 337, 361, 368] [19, 76, 112, 151, 193, 302, 368]
[44, 77, 112, 144, 152, 160, 168, 176, 183, 191, 226, 257, 293, 322, 337, 361, 368] [45, 111, 150, 192, 302, 368]
[44, 77, 112, 144, 152, 160, 168, 176, 183, 191, 226, 257, 293, 322, 337, 361, 368] [120, 157, 290, 368]
[44, 77, 112, 144, 152, 160, 168, 176, 183, 191, 226, 257, 293, 322, 337, 361, 368] [109, 157, 368]
[44, 77, 112, 144, 152, 160, 168, 176, 183, 191, 226, 257, 293, 322, 337, 361, 368] [116, 156, 210, 308, 368]
[44, 77, 112, 144, 152, 160, 168, 176, 183, 191, 226, 257, 293, 322, 337, 361, 368] [49, 118, 201, 297, 368]
[18, 49, 81, 111, 147, 194, 260, 298, 320, 368]
[ 41  71 103 132 142 152 161 170 179 189 222 249 282 309 327 356]
[41, 71, 103, 132, 142, 152, 161, 170, 179, 189, 222, 249, 282, 309, 327, 356, 364]
[41, 71, 103, 132, 142, 152, 161, 170, 179, 189, 222, 249, 282, 309, 327, 356, 364] [48, 111, 130, 194, 210, 293, 364]
[41, 71, 103, 132, 142, 152, 161, 170, 179, 189, 222, 249, 282, 309, 327, 356, 364] [33, 105, 132, 189, 282, 327, 364]
[41, 71, 103, 132, 142, 152, 161, 170, 179, 189, 222, 249, 282, 309, 327, 356, 364] [16, 45, 71, 102, 129, 190, 250, 283, 308, 364]
[41, 71, 103, 132, 142, 152, 161, 170, 179, 189, 222, 249, 282, 309, 327, 356, 364] [29, 69, 102, 131, 188, 249, 317, 364]
[41, 71, 103, 132, 142, 152, 161, 170, 179, 189, 222, 249, 282, 309, 327, 356, 364] [99, 364]
[41, 71, 103, 132, 142, 152, 161, 170, 179, 189, 222, 249, 282, 309, 327, 356, 364] [31, 61, 180, 364]
[41, 71, 103, 132, 142, 152, 161, 170, 179, 189, 222, 249, 282, 309, 327, 356, 364] [79, 110, 248, 281, 364]
[41, 71, 103, 132, 142, 152, 161, 170, 179, 189, 222, 249, 282, 309, 327, 356, 364] [32, 111, 241, 281, 364]
[41, 71, 103, 132, 142, 152, 161, 170, 179, 189, 222, 249, 282, 309, 327, 356, 364] [30, 128, 198, 247, 292, 364]
[41, 71, 103, 132, 142, 152, 161, 170, 179, 189, 222, 249, 282, 309, 327, 356, 364] [29, 68, 112, 194, 285, 323, 364]
[41, 71, 103, 132, 142, 152, 161, 170, 179, 189, 222, 249, 282, 309, 327, 356, 364] [38, 104, 190, 284, 321, 364]
[41, 71, 103, 132, 142, 152, 161, 170, 179, 189, 222, 249, 282, 309, 327, 356, 364] [68, 104, 188, 282, 320, 364]
[41, 71, 103, 132, 142, 152, 161, 170, 179, 189, 222, 249, 282, 309, 327, 356, 364] [319, 364]
[41, 71, 103, 132, 142, 152, 161, 170, 179, 189, 222, 249, 282, 309, 327, 356, 364] [110, 364]
[41, 71, 103, 132, 142, 152, 161, 170, 179, 189, 222, 249, 282, 309, 327, 356, 364] [27, 136, 197, 246, 289, 364]
[41, 71, 103, 132, 142, 152, 161, 170, 179, 189, 222, 249, 282, 309, 327, 356, 364] [29, 110, 190, 247, 289, 320, 364]
[16, 45, 71, 102, 129, 190, 250, 283, 308, 364]
[ 42  79 120 147 161 175 182 189 221 257 299 324 336 349 355]
[42, 79, 120, 147, 161, 175, 182, 189, 221, 257, 299, 324, 336, 349, 355, 360]
[42, 79, 120, 147, 161, 175, 182, 189, 221, 257, 299, 324, 336, 349, 355, 360] [17, 55, 124, 191, 310, 360]
[42, 79, 120, 147, 161, 175, 182, 189, 221, 257, 299, 324, 336, 349, 355, 360] [17, 48, 86, 127, 188, 218, 302, 360]
[42, 79, 120, 147, 161, 175, 182, 189, 221, 257, 299, 324, 336, 349, 355, 360] [19, 48, 85, 122, 150, 188, 264, 297, 360]
[42, 79, 120, 147, 161, 175, 182, 189, 221, 257, 299, 324, 336, 349, 355, 360] [37, 75, 121, 151, 187, 214, 255, 296, 327, 360]
[42, 79, 120, 147, 161, 175, 182, 189, 221, 257, 299, 324, 336, 349, 355, 360] [83, 100, 269, 360]
[42, 79, 120, 147, 161, 175, 182, 189, 221, 257, 299, 324, 336, 349, 355, 360] [29, 90, 131, 178, 218, 268, 310, 360]
[42, 79, 120, 147, 161, 175, 182, 189, 221, 257, 299, 324, 336, 349, 355, 360] [87, 360]
[42, 79, 120, 147, 161, 175, 182, 189, 221, 257, 299, 324, 336, 349, 355, 360] [40, 89, 130, 192, 237, 270, 301, 323, 360]
[42, 79, 120, 147, 161, 175, 182, 189, 221, 257, 299, 324, 336, 349, 355, 360] [28, 118, 202, 313, 360]
[42, 79, 120, 147, 161, 175, 182, 189, 221, 257, 299, 324, 336, 349, 355, 360] [45, 127, 195, 304, 360]
[42, 79, 120, 147, 161, 175, 182, 189, 221, 257, 299, 324, 336, 349, 355, 360] [40, 78, 118, 187, 257, 302, 360]
[42, 79, 120, 147, 161, 175, 182, 189, 221, 257, 299, 324, 336, 349, 355, 360] [43, 119, 188, 302, 360]
[42, 79, 120, 147, 161, 175, 182, 189, 221, 257, 299, 324, 336, 349, 355, 360] [360]
[42, 79, 120, 147, 161, 175, 182, 189, 221, 257, 299, 324, 336, 349, 355, 360] [120, 258, 360]
[42, 79, 120, 147, 161, 175, 182, 189, 221, 257, 299, 324, 336, 349, 355, 360] [27, 119, 191, 311, 360]
[42, 79, 120, 147, 161, 175, 182, 189, 221, 257, 299, 324, 336, 349, 355, 360] [28, 49, 87, 128, 190, 299, 360]
[37, 75, 121, 151, 187, 214, 255, 296, 327, 360]
[ 32  56  80 110 134 159 182 204 228 257 280]
[32, 56, 80, 110, 134, 159, 182, 204, 228, 257, 280, 302]
[32, 56, 80, 110, 134, 159, 182, 204, 228, 257, 280, 302] [54, 109, 167, 203, 255, 302]
[32, 56, 80, 110, 134, 159, 182, 204, 228, 257, 280, 302] [11, 53, 87, 110, 158, 239, 255, 302]
[32, 56, 80, 110, 134, 159, 182, 204, 228, 257, 280, 302] [17, 52, 82, 110, 133, 160, 231, 255, 302]
[32, 56, 80, 110, 134, 159, 182, 204, 228, 257, 280, 302] [52, 81, 110, 158, 229, 256, 302]
[32, 56, 80, 110, 134, 159, 182, 204, 228, 257, 280, 302] [101, 197, 302]
[32, 56, 80, 110, 134, 159, 182, 204, 228, 257, 280, 302] [30, 63, 119, 162, 302]
[32, 56, 80, 110, 134, 159, 182, 204, 228, 257, 280, 302] [81, 107, 160, 189, 302]
[32, 56, 80, 110, 134, 159, 182, 204, 228, 257, 280, 302] [30, 79, 171, 302]
[32, 56, 80, 110, 134, 159, 182, 204, 228, 257, 280, 302] [28, 101, 168, 246, 302]
[32, 56, 80, 110, 134, 159, 182, 204, 228, 257, 280, 302] [28, 99, 167, 242, 302]
[32, 56, 80, 110, 134, 159, 182, 204, 228, 257, 280, 302] [99, 121, 154, 242, 302]
[32, 56, 80, 110, 134, 159, 182, 204, 228, 257, 280, 302] [76, 99, 154, 194, 226, 245, 268, 302]
[32, 56, 80, 110, 134, 159, 182, 204, 228, 257, 280, 302] [108, 230, 302]
[32, 56, 80, 110, 134, 159, 182, 204, 228, 257, 280, 302] [99, 302]
[32, 56, 80, 110, 134, 159, 182, 204, 228, 257, 280, 302] [27, 110, 170, 246, 302]
[32, 56, 80, 110, 134, 159, 182, 204, 228, 257, 280, 302] [28, 97, 168, 198, 240, 302]
[17, 52, 82, 110, 133, 160, 231, 255, 302]
[ 39  75 106 133 155 181 216 246 283 307 330]
[39, 75, 106, 133, 155, 181, 216, 246, 283, 307, 330, 354]

                   0         1          2          3
F1          0.771795  0.096903   0.583333   0.956522
AUC         0.795499  0.084663   0.619048   0.958333
FP          0.766667  0.858360   0.000000   3.000000
DD          3.494973  1.709302   1.444444   9.500000
Threshold  10.000000  0.000000  10.000000  10.000000
Covering    0.650811  0.070501   0.490539   0.805065
Runtime     1.496997  0.310618   1.177362   2.904778

[ 28  52  79 126 151 177 203 214 226 238 249 297 304 331]
[28, 52, 79, 126, 151, 177, 203, 214, 226, 238, 249, 297, 304, 331, 347]
[22, 78, 121, 152, 175, 208, 248, 303, 323, 347]
[ 24  48  79 106 125 148 169 199 226 252 271]
[24, 48, 79, 106, 125, 148, 169, 199, 226, 252, 271, 294]
[23, 77, 114, 143, 178, 224, 270, 294]
[ 22  48  78 107 129 155 181 208 235 265 289]
[22, 48, 78, 107, 129, 155, 181, 208, 235, 265, 289, 316]
[19, 50, 78, 104, 155, 180, 235, 265, 291, 316]
[ 28  56  83 110 135 162 196 219 252 275 296]
[28, 56, 83, 110, 135, 162, 196, 219, 252, 275, 296, 320]
[21, 54, 82, 107, 162, 222, 251, 268, 320]
[ 28  52  85 115 142 173 203 228 257 284 304]
[28, 52, 85, 115, 142, 173, 203, 228, 257, 284, 304, 327]
[23, 54, 85, 116, 147, 177, 227, 264, 282, 327]
[ 31  57  82 112 136 163 193 221 247 276 297]
[31, 57, 82, 112, 136, 163, 193, 221, 247, 276, 297, 323]
[22, 33, 45, 82, 111, 163, 218, 248, 276, 323]
[ 28  55  89 117 138 162 188 220 258 284 305]
[28, 55, 89, 117, 138, 162, 188, 220, 258, 284, 305, 328]
[22, 54, 89, 115, 149, 160, 222, 259, 283, 300, 328]
[ 37  68 103 129 153 180 222 260 295 320 343]
[37, 68, 103, 129, 153, 180, 222, 260, 295, 320, 343, 366]
[22, 75, 102, 155, 179, 218, 259, 295, 319, 366]
[ 44  77 112 144 152 160 168 176 183 191 226 257 293 322 337 361]
[44, 77, 112, 144, 152, 160, 168, 176, 183, 191, 226, 257, 293, 322, 337, 361, 368]
[21, 83, 111, 147, 190, 232, 258, 298, 321, 368]
[ 41  71 103 132 142 152 161 170 179 189 222 249 282 309 327 356]
[41, 71, 103, 132, 142, 152, 161, 170, 179, 189, 222, 249, 282, 309, 327, 356, 364]
[27, 73, 104, 132, 188, 250, 280, 317, 364]
[ 42  79 120 147 161 175 182 189 221 257 299 324 336 349 355]
[42, 79, 120, 147, 161, 175, 182, 189, 221, 257, 299, 324, 336, 349, 355, 360]
[37, 49, 84, 118, 149, 191, 216, 257, 298, 325, 360]
[ 32  56  80 110 134 159 182 204 228 257 280]
[32, 56, 80, 110, 134, 159, 182, 204, 228, 257, 280, 302]
[29, 79, 108, 135, 159, 203, 229, 265, 302]
[ 39  75 106 133 155 181 216 246 283 307 330]
[39, 75, 106, 133, 155, 181, 216, 246, 283, 307, 330, 354]
[41, 72, 120, 179, 250, 304, 354]
[ 46  93 137 164 179 196 204 212 256 294 340 365 380 395 402]
[46, 93, 137, 164, 179, 196, 204, 212, 256, 294, 340, 365, 380, 395, 402, 408]
[20, 31, 99, 137, 172, 213, 251, 291, 338, 371, 408]
[ 31  63 100 123 135 149 155 162 195 225 260 283 301]
[31, 63, 100, 123, 135, 149, 155, 162, 195, 225, 260, 283, 301, 321]
[27, 69, 98, 165, 222, 259, 296, 321]
[ 34  72 105 135 144 153 162 170 179 187 222 252 291 320 347]
[34, 72, 105, 135, 144, 153, 162, 170, 179, 187, 222, 252, 291, 320, 347, 372]
[20, 61, 103, 131, 145, 188, 258, 290, 323, 348, 372]
[ 34  68 104 132 159 188 224 258 294 324 343 363 372]
[34, 68, 104, 132, 159, 188, 224, 258, 294, 324, 343, 363, 372, 381]
[21, 67, 112, 132, 159, 188, 260, 295, 322, 350, 381]
[ 38  72 105 141 171 206 243 274 314 352 380]
[38, 72, 105, 141, 171, 206, 243, 274, 314, 352, 380, 409]
[20, 76, 101, 133, 171, 206, 277, 314, 351, 363, 378, 409]
[ 39  83 117 145 170 198 234 268 310 341 358 376 384]
[39, 83, 117, 145, 170, 198, 234, 268, 310, 341, 358, 376, 384, 392]
[21, 50, 85, 117, 140, 169, 197, 228, 265, 309, 336, 362, 392]
[ 37  74 110 138 160 185 229 262 300 329 351]
[37, 74, 110, 138, 160, 185, 229, 262, 300, 329, 351, 376]
[34, 74, 108, 136, 163, 184, 223, 262, 299, 332, 376]
[ 44  87 129 157 165 174 190 209 245 274 312 338 360]
[44, 87, 129, 157, 165, 174, 190, 209, 245, 274, 312, 338, 360, 382]
[22, 52, 87, 130, 168, 213, 269, 309, 345, 382]
[ 32  60 100 126 150 175 209 241 270 297 321]
[32, 60, 100, 126, 150, 175, 209, 241, 270, 297, 321, 344]
[20, 59, 98, 135, 175, 216, 244, 269, 296, 344]
[ 32  58  88 119 142 176 206 232 264 291 317]
[32, 58, 88, 119, 142, 176, 206, 232, 264, 291, 317, 341]
[21, 63, 94, 120, 180, 239, 264, 292, 341]
[ 28  60  98 131 154 178 189 200 232 262 294 326 354]
[28, 60, 98, 131, 154, 178, 189, 200, 232, 262, 294, 326, 354, 383]
[22, 64, 98, 132, 152, 199, 228, 264, 301, 328, 357, 383]
[ 29  53  83 114 137 165 193 219 243 272 294]
[29, 53, 83, 114, 137, 165, 193, 219, 243, 272, 294, 317]
[29, 57, 84, 113, 141, 167, 194, 203, 245, 271, 317]
[ 29  52  80 110 135 160 188 209 233 259 281]
[29, 52, 80, 110, 135, 160, 188, 209, 233, 259, 281, 302]
[20, 53, 79, 109, 160, 230, 273, 302]
[ 31  60  88 117 141 167 194 220 249 277 301]
[31, 60, 88, 117, 141, 167, 194, 220, 249, 277, 301, 325]
[22, 59, 93, 115, 142, 168, 218, 249, 275, 325]
[ 29  55  82 111 136 162 187 209 234 262 284]
[29, 55, 82, 111, 136, 162, 187, 209, 234, 262, 284, 308]
[21, 83, 113, 166, 209, 237, 261, 308]
[ 23  45  70  94 114 135 167 191 220 244 262]
[23, 45, 70, 94, 114, 135, 167, 191, 220, 244, 262, 281]
[69, 135, 163, 194, 222, 256, 281]
[ 23  48  72  98 105 115 121 129 137 145 168 193 219 245 259 282]
[23, 48, 72, 98, 105, 115, 121, 129, 137, 145, 168, 193, 219, 245, 259, 282, 288]
[20, 73, 103, 145, 172, 187, 219, 254, 288]
<wrappers.OnlineRuLSIF object at 0x77eef877cd10>

                   0         1          2          3
F1          0.790937  0.091066   0.615385   0.956522
AUC         0.813966  0.077474   0.678571   0.958333
FP          0.600000  0.723974   0.000000   2.000000
DD          3.175259  1.093156   1.100000   6.454545
Threshold  10.000000  0.000000  10.000000  10.000000
Covering    0.669925  0.078764   0.534278   0.840636
Runtime     3.599403  0.619468   2.710591   5.389486

CPU times: user 2.77 s, sys: 615 ms, total: 3.39 s
Wall time: 2min 35s

In [14]:
%%time

dir_path = "../data/HAR_NEW/"


models = [wrappers.OrigRuLSIF(alpha=0.1, kernel_num=10, window_size=20, step=10, periods=1, height=0.1)]


for amodel in models:
    report = run_test_on_dataset(dir_path, amodel, downsample=1, margin=10, verbose=0, sigma=1.0,seed=12345)
    print(amodel)
    for rep in report:
        display(rep)

[ 28  52  79 126 151 177 203 214 226 238 249 297 304 331]
[28, 52, 79, 126, 151, 177, 203, 214, 226, 238, 249, 297, 304, 331, 347]
[13, 43, 63, 83, 113, 143, 173, 203, 243, 293, 347]
[ 24  48  79 106 125 148 169 199 226 252 271]
[24, 48, 79, 106, 125, 148, 169, 199, 226, 252, 271, 294]
[13, 73, 93, 113, 133, 163, 193, 223, 243, 294]
[ 22  48  78 107 129 155 181 208 235 265 289]
[22, 48, 78, 107, 129, 155, 181, 208, 235, 265, 289, 316]
[13, 43, 73, 103, 123, 153, 183, 203, 223, 253, 273, 316]
[ 28  56  83 110 135 162 196 219 252 275 296]
[28, 56, 83, 110, 135, 162, 196, 219, 252, 275, 296, 320]
[23, 53, 73, 103, 123, 153, 183, 213, 243, 283, 320]
[ 28  52  85 115 142 173 203 228 257 284 304]
[28, 52, 85, 115, 142, 173, 203, 228, 257, 284, 304, 327]
[23, 43, 73, 133, 163, 193, 223, 243, 273, 327]
[ 31  57  82 112 136 163 193 221 247 276 297]
[31, 57, 82, 112, 136, 163, 193, 221, 247, 276, 297, 323]
[23, 53, 73, 103, 133, 153, 183, 213, 243, 273, 323]
[ 28  55  89 117 138 162 188 220 258 284 305]
[28, 55, 89, 117, 138, 162, 188, 220, 258, 284, 305, 328]
[23, 53, 83, 113, 133, 153, 183, 203, 253, 273, 328]
[ 37  68 103 129 153 180 222 260 295 320 343]
[37, 68, 103, 129, 153, 180, 222, 260, 295, 320, 343, 366]
[23, 63, 93, 123, 143, 173, 203, 223, 253, 293, 313, 366]
[ 44  77 112 144 152 160 168 176 183 191 226 257 293 322 337 361]
[44, 77, 112, 144, 152, 160, 168, 176, 183, 191, 226, 257, 293, 322, 337, 361, 368]
[23, 43, 73, 103, 133, 183, 253, 283, 313, 368]
[ 41  71 103 132 142 152 161 170 179 189 222 249 282 309 327 356]
[41, 71, 103, 132, 142, 152, 161, 170, 179, 189, 222, 249, 282, 309, 327, 356, 364]
[23, 63, 93, 123, 183, 243, 273, 303, 364]
[ 42  79 120 147 161 175 182 189 221 257 299 324 336 349 355]
[42, 79, 120, 147, 161, 175, 182, 189, 221, 257, 299, 324, 336, 349, 355, 360]
[33, 73, 113, 153, 183, 213, 253, 293, 360]
[ 32  56  80 110 134 159 182 204 228 257 280]
[32, 56, 80, 110, 134, 159, 182, 204, 228, 257, 280, 302]
[23, 73, 103, 123, 153, 203, 223, 243, 302]
[ 39  75 106 133 155 181 216 246 283 307 330]
[39, 75, 106, 133, 155, 181, 216, 246, 283, 307, 330, 354]
[33, 63, 93, 133, 173, 203, 233, 273, 303, 354]
[ 46  93 137 164 179 196 204 212 256 294 340 365 380 395 402]
[46, 93, 137, 164, 179, 196, 204, 212, 256, 294, 340, 365, 380, 395, 402, 408]
[13, 33, 63, 83, 133, 163, 203, 243, 293, 333, 408]
[ 31  63 100 123 135 149 155 162 195 225 260 283 301]
[31, 63, 100, 123, 135, 149, 155, 162, 195, 225, 260, 283, 301, 321]
[23, 53, 93, 113, 153, 183, 213, 253, 287, 321]
[ 34  72 105 135 144 153 162 170 179 187 222 252 291 320 347]
[34, 72, 105, 135, 144, 153, 162, 170, 179, 187, 222, 252, 291, 320, 347, 372]
[23, 63, 93, 133, 173, 213, 253, 283, 323, 372]
[ 34  68 104 132 159 188 224 258 294 324 343 363 372]
[34, 68, 104, 132, 159, 188, 224, 258, 294, 324, 343, 363, 372, 381]
[23, 43, 63, 93, 133, 153, 183, 203, 253, 283, 323, 381]
[ 38  72 105 141 171 206 243 274 314 352 380]
[38, 72, 105, 141, 171, 206, 243, 274, 314, 352, 380, 409]
[23, 63, 103, 133, 163, 203, 233, 273, 293, 313, 353, 409]
[ 39  83 117 145 170 198 234 268 310 341 358 376 384]
[39, 83, 117, 145, 170, 198, 234, 268, 310, 341, 358, 376, 384, 392]
[13, 33, 53, 73, 113, 143, 163, 193, 223, 263, 303, 343, 392]
[ 37  74 110 138 160 185 229 262 300 329 351]
[37, 74, 110, 138, 160, 185, 229, 262, 300, 329, 351, 376]
[23, 43, 63, 103, 153, 183, 223, 253, 293, 323, 376]
[ 44  87 129 157 165 174 190 209 245 274 312 338 360]
[44, 87, 129, 157, 165, 174, 190, 209, 245, 274, 312, 338, 360, 382]
[13, 43, 83, 133, 153, 203, 223, 263, 283, 303, 333, 382]
[ 32  60 100 126 150 175 209 241 270 297 321]
[32, 60, 100, 126, 150, 175, 209, 241, 270, 297, 321, 344]
[23, 53, 93, 133, 163, 203, 233, 263, 293, 344]
[ 32  58  88 119 142 176 206 232 264 291 317]
[32, 58, 88, 119, 142, 176, 206, 232, 264, 291, 317, 341]
[13, 53, 83, 113, 133, 163, 223, 253, 283, 341]
[ 28  60  98 131 154 178 189 200 232 262 294 326 354]
[28, 60, 98, 131, 154, 178, 189, 200, 232, 262, 294, 326, 354, 383]
[13, 53, 93, 123, 173, 193, 223, 253, 283, 313, 343, 383]
[ 29  53  83 114 137 165 193 219 243 272 294]
[29, 53, 83, 114, 137, 165, 193, 219, 243, 272, 294, 317]
[23, 43, 83, 103, 123, 163, 193, 213, 243, 263, 317]
[ 29  52  80 110 135 160 188 209 233 259 281]
[29, 52, 80, 110, 135, 160, 188, 209, 233, 259, 281, 302]
[13, 43, 73, 103, 123, 153, 203, 223, 253, 302]
[ 31  60  88 117 141 167 194 220 249 277 301]
[31, 60, 88, 117, 141, 167, 194, 220, 249, 277, 301, 325]
[23, 53, 73, 93, 113, 133, 163, 183, 213, 243, 263, 325]
[ 29  55  82 111 136 162 187 209 234 262 284]
[29, 55, 82, 111, 136, 162, 187, 209, 234, 262, 284, 308]
[43, 73, 103, 123, 153, 203, 223, 253, 308]
[ 23  45  70  94 114 135 167 191 220 244 262]
[23, 45, 70, 94, 114, 135, 167, 191, 220, 244, 262, 281]
[13, 53, 123, 153, 193, 213, 243, 281]
[ 23  48  72  98 105 115 121 129 137 145 168 193 219 245 259 282]
[23, 48, 72, 98, 105, 115, 121, 129, 137, 145, 168, 193, 219, 245, 259, 282, 288]
[13, 43, 63, 93, 133, 213, 243, 288]
<wrappers.OrigRuLSIF object at 0x77eef83f06e0>

                   0         1          2          3
F1          0.703356  0.105488   0.518519   0.956522
AUC         0.718689  0.099320   0.536932   0.958333
FP          2.166667  1.147211   0.000000   4.000000
DD          7.015580  1.077376   4.818182   9.090909
Threshold  10.000000  0.000000  10.000000  10.000000
Covering    0.543135  0.060513   0.416439   0.652040
Runtime     0.105930  0.012183   0.087316   0.129055

CPU times: user 1.48 s, sys: 152 ms, total: 1.63 s
Wall time: 5.06 s

In [ ]:
%%time

dir_path = "../../datasets/has2023DataR/"


models = [wrappers.OnlineCLF(lag_size=250, height=.1),
          wrappers.OnlineRuLSIF(lag_size=250, height=.1)]
          #wrappers.OrigRuLSIF(alpha=0.1, kernel_num=10, window_size=100, step=10, periods=1, height=0.1)]


for amodel in models:
    report = run_test_on_dataset(dir_path, amodel, downsample=1, margin=100, verbose=0, sigma=1.0,seed=12345)
    print(amodel)
    for rep in report:
        display(rep)

[1275 2746 4184]
[1275, 2746, 4184, 5597]
[1275, 2746, 4184, 5597] [1297, 1625, 1777, 2317, 2772, 4273, 4681, 5314, 5597]
[1275, 2746, 4184, 5597] [143, 967, 1293, 1610, 1753, 1934, 2320, 2768, 4284, 4657, 5016, 5314, 5597]
[1275, 2746, 4184, 5597] [220, 1290, 1770, 2322, 2758, 3330, 4284, 4702, 5034, 5314, 5597]
[1275, 2746, 4184, 5597] [238, 594, 750, 1279, 1783, 2289, 2733, 3136, 3330, 3547, 4268, 4653, 5029, 5314, 5597]
[1275, 2746, 4184, 5597] [844, 1395, 2864, 4330, 4809, 5597]
[1275, 2746, 4184, 5597] [421, 868, 1326, 1863, 2758, 4289, 4810, 5314, 5597]
[1275, 2746, 4184, 5597] [421, 864, 1299, 2758, 3538, 4301, 4772, 5287, 5597]
[1275, 2746, 4184, 5597] [436, 965, 1287, 2205, 2768, 3363, 4206, 5195, 5597]
[1275, 2746, 4184, 5597] [145, 1296, 1769, 2270, 2766, 4267, 4669, 5305, 5597]
[1275, 2746, 4184, 5597] [709, 1290, 1944, 2323, 2759, 3345, 3794, 4277, 4638, 5035, 5305, 5597]
[1275, 2746, 4184, 5597] [298, 1286, 1788, 2313, 2746, 4271, 4651, 5042, 5305, 5597]
[1275, 2746, 4184, 5597] [243, 596, 779, 1282, 1900, 2331, 2739, 3163, 3499, 4271, 4660, 4974, 5305, 5597]
[1275, 2746, 4184, 5597] [1330, 2778, 3091, 4313, 4818, 5597]
[1275, 2746, 4184, 5597] [1300, 2770, 4291, 5597]
[1275, 2746, 4184, 5597] [143, 1294, 1790, 2315, 2768, 4268, 5305, 5597]
[1275, 2746, 4184, 5597] [767, 1286, 1916, 2339, 2757, 3184, 3629, 3814, 4275, 5017, 5305, 5597]
[1300, 2770, 4291, 5597]
[]
[954]
[954] [435, 954]
[954] [268, 954]
[954] [262, 954]
[954] [276, 954]
[954] [954]
[954] [431, 954]
[954] [426, 954]
[954] [435, 954]
[954] [429, 954]
[954] [272, 954]
[954] [290, 954]
[954] [291, 954]
[954] [566, 954]
[954] [455, 954]
[954] [430, 954]
[954] [274, 954]
[954]
[1513 1935]
[1513, 1935, 3423]
[1513, 1935, 3423] [1579, 3140, 3423]
[1513, 1935, 3423] [141, 784, 981, 1583, 2430, 2747, 3140, 3423]
[1513, 1935, 3423] [238, 888, 1577, 2774, 3140, 3423]
[1513, 1935, 3423] [233, 563, 914, 1548, 2476, 2814, 3140, 3423]
[1513, 1935, 3423] [812, 1643, 2545, 3423]
[1513, 1935, 3423] [426, 846, 1601, 2556, 3423]
[1513, 1935, 3423] [428, 817, 1600, 3423]
[1513, 1935, 3423] [404, 779, 1207, 1529, 1926, 2775, 3100, 3423]
[1513, 1935, 3423] [1584, 3131, 3423]
[1513, 1935, 3423] [802, 1580, 2365, 2756, 3131, 3423]
[1513, 1935, 3423] [244, 660, 983, 1564, 2540, 3131, 3423]
[1513, 1935, 3423] [257, 988, 1575, 2540, 2960, 3131, 3423]
[1513, 1935, 3423] [1589, 3423]
[1513, 1935, 3423] [1608, 1927, 3131, 3423]
[1513, 1935, 3423] [1581, 3131, 3423]
[1513, 1935, 3423] [137, 800, 908, 1571, 2451, 2609, 2747, 3131, 3423]
[1608, 1927, 3131, 3423]
[1429 2844 4098]
[1429, 2844, 4098, 5952]
[1429, 2844, 4098, 5952] [1469, 2864, 4119, 5952]
[1429, 2844, 4098, 5952] [1451, 2361, 2853, 3292, 4115, 4508, 5083, 5269, 5637, 5952]
[1429, 2844, 4098, 5952] [1448, 2400, 2858, 4116, 4530, 4955, 5084, 5269, 5646, 5952]
[1429, 2844, 4098, 5952] [114, 850, 1444, 2092, 2404, 2849, 3312, 4106, 4526, 4929, 5102, 5273, 5480, 5952]
[1429, 2844, 4098, 5952] [2860, 5525, 5952]
[1429, 2844, 4098, 5952] [1159, 1477, 2142, 2322, 2857, 3366, 4095, 5669, 5952]
[1429, 2844, 4098, 5952] [814, 1448, 2856, 4099, 5057, 5378, 5659, 5952]
[1429, 2844, 4098, 5952] [858, 1437, 2215, 2847, 3963, 4492, 4632, 5067, 5952]
[1429, 2844, 4098, 5952] [1456, 2861, 4116, 5952]
[1429, 2844, 4098, 5952] [1450, 2244, 2855, 3695, 4114, 4599, 5345, 5952]
[1429, 2844, 4098, 5952] [1452, 2108, 2394, 2857, 3599, 4119, 4577, 4952, 5076, 5286, 5473, 5952]
[1429, 2844, 4098, 5952] [101, 1455, 2279, 2854, 3285, 4121, 4727, 4920, 5095, 5286, 5466, 5952]
[1429, 2844, 4098, 5952] [1505, 2868, 4153, 5952]
[1429, 2844, 4098, 5952] [1476, 2862, 4143, 5952]
[1429, 2844, 4098, 5952] [1462, 2859, 4119, 5952]
[1429, 2844, 4098, 5952] [1452, 2132, 2255, 2855, 3401, 4124, 4686, 4967, 5353, 5627, 5952]
[1456, 2861, 4116, 5952]
[]
[6200]
[6200] [264, 593, 774, 1280, 1872, 2222, 2616, 3526, 4021, 6200]
[6200] [233, 545, 1270, 1880, 2203, 2706, 3522, 3963, 6200]
[6200] [233, 554, 1278, 1843, 2207, 2599, 3515, 3965, 4664, 5017, 5288, 5589, 6200]
[6200] [230, 548, 1281, 1842, 2200, 2875, 3495, 4036, 4563, 4928, 5206, 5519, 6200]
[6200] [162, 3657, 6200]
[6200] [176, 816, 1322, 1862, 2299, 3393, 4453, 5041, 5430, 5813, 6200]
[6200] [233, 753, 1309, 1733, 2193, 3389, 4159, 4353, 4531, 4690, 5350, 5811, 6200]
[6200] [184, 461, 821, 1236, 1709, 2170, 2878, 3059, 3373, 3747, 4176, 4361, 4587, 5250, 5633, 6200]
[6200] [263, 599, 1277, 1841, 2208, 2624, 3519, 3979, 5698, 6200]
[6200] [251, 571, 1284, 1882, 2209, 2677, 3507, 4041, 6200]
[6200] [262, 559, 1271, 1758, 2196, 2597, 3513, 3989, 4828, 5238, 5678, 6200]
[6200] [257, 556, 770, 2181, 2590, 3475, 3987, 4956, 5883, 6200]
[6200] [343, 946, 1287, 6200]
[6200] [271, 805, 1291, 1874, 2307, 2616, 3567, 4121, 6200]
[6200] [275, 608, 1281, 1850, 2212, 2633, 3520, 3987, 6200]
[6200] [240, 555, 1282, 2207, 2722, 3513, 3979, 6200]
[343, 946, 1287, 6200]
[4175 5290 6760 7750]
[4175, 5290, 6760, 7750, 8740]
[4175, 5290, 6760, 7750, 8740] [232, 932, 4303, 5335, 6642, 7778, 8740]
[4175, 5290, 6760, 7750, 8740] [230, 362, 922, 3528, 4303, 5313, 6543, 6761, 7074, 7259, 7408, 7788, 8740]
[4175, 5290, 6760, 7750, 8740] [231, 361, 917, 4324, 5330, 5804, 6214, 6756, 7239, 7445, 7760, 8740]
[4175, 5290, 6760, 7750, 8740] [233, 915, 2259, 2603, 2989, 4299, 5316, 5832, 6219, 6752, 7255, 7444, 7753, 8740]
[4175, 5290, 6760, 7750, 8740] [913, 4433, 6240, 7809, 8740]
[4175, 5290, 6760, 7750, 8740] [172, 1036, 2328, 2694, 3501, 4443, 5384, 5799, 6247, 6752, 6859, 7767, 8323, 8740]
[4175, 5290, 6760, 7750, 8740] [182, 877, 1716, 2324, 3356, 3661, 4138, 4445, 5365, 5702, 6231, 6667, 7759, 8195, 8309, 8740]
[4175, 5290, 6760, 7750, 8740] [50, 907, 1068, 1724, 2179, 2639, 3259, 3440, 4448, 4785, 4924, 5349, 6118, 6712, 7051, 7758, 8740]
[4175, 5290, 6760, 7750, 8740] [259, 939, 4350, 5311, 6648, 7801, 8740]
[4175, 5290, 6760, 7750, 8740] [243, 923, 1496, 2151, 2701, 2820, 3370, 4325, 5330, 6213, 6884, 7091, 7294, 7423, 7767, 8448, 8740]
[4175, 5290, 6760, 7750, 8740] [258, 923, 1496, 2392, 2963, 4318, 5334, 5774, 6209, 6907, 7225, 7425, 7756, 8176, 8740]
[4175, 5290, 6760, 7750, 8740] [258, 923, 1504, 2171, 2410, 2546, 2926, 3552, 4307, 5323, 6202, 6911, 7256, 7748, 8740]
[4175, 5290, 6760, 7750, 8740] [1074, 4478, 5433, 7838, 8740]
[4175, 5290, 6760, 7750, 8740] [365, 947, 4287, 5400, 7821, 8740]
[4175, 5290, 6760, 7750, 8740] [251, 927, 4323, 5327, 6757, 7779, 8740]
[4175, 5290, 6760, 7750, 8740] [238, 920, 2942, 4310, 5335, 6849, 7048, 7221, 7468, 7775, 8448, 8740]
[251, 927, 4323, 5327, 6757, 7779, 8740]
[1525 3070 4320 5690 6930]
[1525, 3070, 4320, 5690, 6930, 8260]
[1525, 3070, 4320, 5690, 6930, 8260] [944, 1543, 3087, 4395, 5716, 6952, 8260]
[1525, 3070, 4320, 5690, 6930, 8260] [428, 842, 1537, 1880, 2152, 2422, 2599, 3060, 4370, 5158, 5702, 6121, 6952, 7977, 8260]
[1525, 3070, 4320, 5690, 6930, 8260] [450, 915, 1538, 1976, 2286, 3049, 3537, 4365, 5702, 6188, 6947, 7977, 8260]
[1525, 3070, 4320, 5690, 6930, 8260] [435, 879, 1528, 2261, 3051, 3718, 4357, 5103, 5697, 6155, 6949, 7977, 8260]
[1525, 3070, 4320, 5690, 6930, 8260] [1549, 1879, 2226, 2359, 4400, 5705, 6043, 6668, 8260]
[1525, 3070, 4320, 5690, 6930, 8260] [142, 1217, 1545, 1862, 2173, 3055, 3500, 4373, 5393, 5711, 6193, 6961, 8260]
[1525, 3070, 4320, 5690, 6930, 8260] [146, 868, 1544, 1894, 2168, 2791, 3091, 3514, 4373, 5241, 5388, 5740, 6239, 6935, 7446, 8260]
[1525, 3070, 4320, 5690, 6930, 8260] [934, 1531, 1922, 2692, 3512, 4388, 5114, 5720, 6941, 7478, 7651, 7853, 8260]
[1525, 3070, 4320, 5690, 6930, 8260] [418, 923, 1542, 2637, 3073, 4385, 5712, 6950, 8260]
[1525, 3070, 4320, 5690, 6930, 8260] [426, 876, 1534, 2725, 3044, 3535, 4357, 4777, 5130, 5701, 6948, 7968, 8260]
[1525, 3070, 4320, 5690, 6930, 8260] [396, 873, 1113, 1534, 2252, 2729, 3052, 3514, 3714, 4365, 4762, 5135, 5700, 6108, 6303, 6481, 6948, 7719, 8260]
[1525, 3070, 4320, 5690, 6930, 8260] [458, 936, 1527, 2186, 3091, 3756, 4360, 4896, 5233, 5697, 6305, 6949, 7577, 7968, 8260]
[1525, 3070, 4320, 5690, 6930, 8260] [1553, 4429, 5716, 6956, 8260]
[1525, 3070, 4320, 5690, 6930, 8260] [490, 942, 1543, 3116, 4429, 5716, 6982, 8260]
[1525, 3070, 4320, 5690, 6930, 8260] [436, 930, 1542, 3077, 4374, 5709, 6072, 6957, 7968, 8260]
[1525, 3070, 4320, 5690, 6930, 8260] [460, 785, 1536, 2408, 3053, 4365, 4774, 5170, 5705, 6056, 6944, 8260]
[944, 1543, 3087, 4395, 5716, 6952, 8260]
[1473 2820]
[1473, 2820, 4296]
[1473, 2820, 4296] [146, 1499, 1822, 2865, 3236, 4296]
[1473, 2820, 4296] [143, 1497, 2304, 2846, 3217, 3997, 4296]
[1473, 2820, 4296] [227, 877, 1492, 1786, 2309, 2840, 3212, 3995, 4296]
[1473, 2820, 4296] [205, 560, 886, 1508, 1793, 2306, 2820, 3235, 3971, 4296]
[1473, 2820, 4296] [811, 1609, 3896, 4296]
[1473, 2820, 4296] [101, 845, 1555, 2190, 2862, 3398, 3790, 4296]
[1473, 2820, 4296] [104, 817, 1552, 2851, 3362, 4296]
[1473, 2820, 4296] [120, 1583, 2173, 2866, 3664, 4001, 4296]
[1473, 2820, 4296] [162, 1497, 2867, 3226, 3996, 4296]
[1473, 2820, 4296] [132, 1497, 2340, 2850, 3212, 3969, 4296]
[1473, 2820, 4296] [150, 1492, 2166, 2831, 3212, 3954, 4296]
[1473, 2820, 4296] [220, 652, 1481, 2092, 2824, 3214, 3865, 4296]
[1473, 2820, 4296] [1490, 2889, 4296]
[1473, 2820, 4296] [239, 1494, 2874, 3323, 4296]
[1473, 2820, 4296] [163, 1496, 2861, 3234, 3870, 4296]
[1473, 2820, 4296] [122, 1026, 1493, 2321, 2847, 3212, 3889, 4296]
[1490, 2889, 4296]
[1575 3125]
[1575, 3125, 4504]
[1575, 3125, 4504] [304, 1594, 3143, 4504]
[1575, 3125, 4504] [318, 1030, 1590, 2044, 3139, 4070, 4504]
[1575, 3125, 4504] [495, 989, 1583, 2003, 3145, 3982, 4167, 4504]
[1575, 3125, 4504] [510, 1051, 1573, 2196, 2322, 2414, 3130, 3866, 4138, 4504]
[1575, 3125, 4504] [3207, 3956, 4504]
[1575, 3125, 4504] [335, 1598, 2241, 3140, 4123, 4504]
[1575, 3125, 4504] [326, 638, 1588, 2231, 2733, 3142, 3900, 4062, 4504]
[1575, 3125, 4504] [361, 661, 830, 1607, 2243, 2817, 3217, 4054, 4504]
[1575, 3125, 4504] [346, 650, 1592, 2008, 3142, 4504]
[1575, 3125, 4504] [248, 1587, 2003, 3138, 3648, 3832, 4023, 4159, 4504]
[1575, 3125, 4504] [256, 1006, 1579, 2029, 2768, 3143, 3836, 4504]
[1575, 3125, 4504] [260, 992, 1572, 2016, 2357, 3138, 4133, 4504]
[1575, 3125, 4504] [1613, 1999, 3145, 4504]
[1575, 3125, 4504] [489, 1097, 1600, 2084, 3146, 4504]
[1575, 3125, 4504] [348, 643, 1591, 2013, 3142, 3841, 4504]
[1575, 3125, 4504] [264, 1584, 2015, 2391, 2686, 3135, 3735, 4212, 4504]
[304, 1594, 3143, 4504]
[1290]
[1290, 2860]
[1290, 2860] [148, 1312, 2159, 2325, 2860]
[1290, 2860] [137, 924, 1305, 2150, 2860]
[1290, 2860] [162, 456, 906, 1301, 1691, 2148, 2577, 2860]
[1290, 2860] [256, 450, 876, 1296, 1680, 1976, 2577, 2860]
[1290, 2860] [1301, 2157, 2860]
[1290, 2860] [139, 635, 1310, 2172, 2860]
[1290, 2860] [144, 822, 1314, 2175, 2860]
[1290, 2860] [223, 707, 1289, 1799, 2193, 2340, 2860]
[1290, 2860] [265, 432, 948, 1309, 1696, 1966, 2320, 2860]
[1290, 2860] [311, 774, 1298, 1697, 2114, 2545, 2860]
[1290, 2860] [247, 820, 1298, 1686, 2166, 2296, 2860]
[1290, 2860] [260, 757, 1293, 1674, 2169, 2860]
[1290, 2860] [1318, 2313, 2860]
[1290, 2860] [137, 511, 1319, 2314, 2860]
[1290, 2860] [263, 434, 951, 1308, 1688, 1980, 2155, 2324, 2860]
[1290, 2860] [366, 765, 1301, 1699, 1985, 2313, 2860]
[1318, 2313, 2860]
[1291 2884 4272 5977]
[1291, 2884, 4272, 5977, 7238]
[1291, 2884, 4272, 5977, 7238] [314, 1310, 1703, 1898, 2901, 4286, 5995, 6521, 7238]
[1291, 2884, 4272, 5977, 7238] [263, 843, 1296, 1878, 2435, 2894, 4281, 4659, 5142, 5989, 6525, 7238]
[1291, 2884, 4272, 5977, 7238] [275, 847, 1297, 1877, 2298, 2896, 3542, 4280, 5143, 5988, 6519, 7238]
[1291, 2884, 4272, 5977, 7238] [269, 1282, 1865, 2418, 2889, 3512, 4272, 4680, 4933, 5058, 5384, 5576, 5984, 6503, 7238]
[1291, 2884, 4272, 5977, 7238] [344, 1363, 2913, 4380, 6016, 6492, 7238]
[1291, 2884, 4272, 5977, 7238] [332, 1312, 2909, 3471, 4288, 5693, 6020, 6498, 7238]
[1291, 2884, 4272, 5977, 7238] [323, 659, 852, 1015, 1318, 1902, 2160, 2908, 3379, 3669, 4283, 5344, 6011, 6507, 7238]
[1291, 2884, 4272, 5977, 7238] [256, 476, 828, 998, 1303, 2223, 2892, 3540, 3734, 3906, 4276, 5238, 5984, 6529, 7238]
[1291, 2884, 4272, 5977, 7238] [315, 1304, 1707, 1883, 2896, 3591, 4282, 5989, 6534, 7238]
[1291, 2884, 4272, 5977, 7238] [289, 855, 1287, 1874, 2417, 2891, 3409, 4279, 4662, 5169, 5986, 6523, 7238]
[1291, 2884, 4272, 5977, 7238] [286, 859, 1286, 1693, 1868, 2327, 2890, 3542, 4275, 4733, 5445, 5985, 6517, 7238]
[1291, 2884, 4272, 5977, 7238] [286, 849, 1283, 1875, 2037, 2890, 3717, 4264, 5147, 5980, 6514, 6910, 7238]
[1291, 2884, 4272, 5977, 7238] [324, 1316, 2914, 4340, 6009, 6504, 7238]
[1291, 2884, 4272, 5977, 7238] [326, 1319, 2903, 4295, 5999, 7238]
[1291, 2884, 4272, 5977, 7238] [314, 1310, 1697, 1901, 2901, 3752, 4283, 4652, 5995, 6530, 7238]
[1291, 2884, 4272, 5977, 7238] [283, 1298, 1874, 2465, 2889, 3803, 4278, 5167, 5985, 6528, 7238]
[326, 1319, 2903, 4295, 5999, 7238]
[1443 1857]
[1443, 1857, 2781]
[1443, 1857, 2781] [1468, 1904, 2335, 2781]
[1443, 1857, 2781] [226, 1463, 1904, 2781]
[1443, 1857, 2781] [247, 790, 1015, 1458, 1918, 2394, 2781]
[1443, 1857, 2781] [229, 666, 796, 1007, 1129, 1461, 1947, 2053, 2781]
[1443, 1857, 2781] [859, 1469, 2147, 2498, 2781]
[1443, 1857, 2781] [419, 997, 1461, 1798, 2181, 2781]
[1443, 1857, 2781] [420, 878, 1461, 1827, 2781]
[1443, 1857, 2781] [247, 839, 1444, 1800, 2781]
[1443, 1857, 2781] [1467, 1891, 2781]
[1443, 1857, 2781] [222, 612, 1463, 1884, 2781]
[1443, 1857, 2781] [258, 838, 1455, 1886, 2489, 2781]
[1443, 1857, 2781] [260, 675, 1067, 1452, 1917, 2489, 2781]
[1443, 1857, 2781] [1473, 2102, 2392, 2781]
[1443, 1857, 2781] [244, 1469, 1955, 2288, 2781]
[1443, 1857, 2781] [142, 1467, 1893, 2781]
[1443, 1857, 2781] [142, 1459, 1875, 2781]
[1467, 1891, 2781]
[1611 2979]
[1611, 2979, 4111]
[1611, 2979, 4111] [1630, 3008, 4111]
[1611, 2979, 4111] [1624, 2475, 2992, 4111]
[1611, 2979, 4111] [900, 1625, 2160, 2309, 2992, 3815, 4111]
[1611, 2979, 4111] [395, 904, 1048, 1616, 2156, 2308, 2992, 3748, 4111]
[1611, 2979, 4111] [1648, 4111]
[1611, 2979, 4111] [144, 1223, 1627, 2653, 2988, 3476, 4111]
[1611, 2979, 4111] [147, 1629, 2167, 2983, 3356, 3515, 3679, 4111]
[1611, 2979, 4111] [892, 1248, 1618, 2176, 2654, 2984, 3445, 3659, 4111]
[1611, 2979, 4111] [1627, 2162, 2322, 3008, 4111]
[1611, 2979, 4111] [398, 785, 1619, 2986, 3521, 3819, 4111]
[1611, 2979, 4111] [398, 918, 1618, 2334, 2998, 4111]
[1611, 2979, 4111] [269, 454, 933, 1056, 1620, 1974, 2177, 2593, 2975, 3732, 4111]
[1611, 2979, 4111] [1640, 2149, 3105, 4111]
[1611, 2979, 4111] [1635, 3044, 4111]
[1611, 2979, 4111] [1628, 3003, 4111]
[1611, 2979, 4111] [907, 1218, 1623, 2279, 2993, 3719, 4111]
[1628, 3003, 4111]
[]
[1303]
[1303] [86, 487, 1017, 1303]
[1303] [337, 1020, 1303]
[1303] [347, 1303]
[1303] [296, 1303]
[1303] [913, 1303]
[1303] [81, 611, 966, 1303]
[1303] [142, 620, 781, 964, 1303]
[1303] [189, 472, 980, 1303]
[1303] [139, 471, 986, 1303]
[1303] [325, 1011, 1303]
[1303] [350, 1303]
[1303] [343, 1303]
[1303] [578, 973, 1303]
[1303] [72, 492, 990, 1303]
[1303] [89, 484, 997, 1303]
[1303] [306, 1011, 1303]
[296, 1303]
[1440 3006 4383 4862 6381]
[1440, 3006, 4383, 4862, 6381, 7948]
[1440, 3006, 4383, 4862, 6381, 7948] [146, 1465, 3027, 4442, 6402, 7948]
[1440, 3006, 4383, 4862, 6381, 7948] [144, 807, 1455, 3019, 4444, 6404, 7463, 7948]
[1440, 3006, 4383, 4862, 6381, 7948] [140, 885, 1455, 2287, 3019, 4444, 6393, 7114, 7447, 7948]
[1440, 3006, 4383, 4862, 6381, 7948] [149, 1037, 1454, 1860, 2267, 3012, 3589, 4435, 5523, 5984, 6378, 7402, 7948]
[1440, 3006, 4383, 4862, 6381, 7948] [1544, 3050, 6404, 7948]
[1440, 3006, 4383, 4862, 6381, 7948] [827, 1003, 1544, 2148, 3017, 3720, 4403, 4949, 5427, 6401, 6978, 7948]
[1440, 3006, 4383, 4862, 6381, 7948] [891, 1446, 2108, 3023, 4398, 4751, 5411, 5571, 6101, 6397, 7295, 7948]
[1440, 3006, 4383, 4862, 6381, 7948] [275, 619, 863, 1502, 2150, 3013, 4442, 4875, 5252, 6114, 6400, 7475, 7948]
[1440, 3006, 4383, 4862, 6381, 7948] [149, 1460, 3024, 4436, 6404, 7948]
[1440, 3006, 4383, 4862, 6381, 7948] [147, 952, 1453, 1857, 2004, 3019, 3735, 4438, 6389, 6710, 7948]
[1440, 3006, 4383, 4862, 6381, 7948] [138, 612, 1451, 1820, 3017, 4446, 6396, 6943, 7572, 7948]
[1440, 3006, 4383, 4862, 6381, 7948] [239, 755, 1451, 1958, 2125, 2428, 3009, 3948, 4424, 5322, 5835, 6382, 6828, 7255, 7948]
[1440, 3006, 4383, 4862, 6381, 7948] [1543, 3064, 4401, 6401, 7948]
[1440, 3006, 4383, 4862, 6381, 7948] [139, 1467, 3037, 4414, 4764, 6399, 7948]
[1440, 3006, 4383, 4862, 6381, 7948] [143, 1459, 3027, 4429, 6400, 7948]
[1440, 3006, 4383, 4862, 6381, 7948] [141, 931, 1453, 1903, 2370, 3024, 4453, 6390, 7124, 7416, 7948]
[139, 1467, 3037, 4414, 4764, 6399, 7948]
[1542 3072 4590 6057 7485 8976]
[1542, 3072, 4590, 6057, 7485, 8976, 10462]
[1542, 3072, 4590, 6057, 7485, 8976, 10462] [1565, 2048, 2405, 3078, 3875, 4613, 6055, 7510, 8989, 10462]
[1542, 3072, 4590, 6057, 7485, 8976, 10462] [420, 569, 1554, 2163, 2477, 3053, 3877, 4607, 5124, 5544, 6049, 6267, 6600, 7091, 7508, 7894, 8530, 8980, 9331, 9844, 10462]
[1542, 3072, 4590, 6057, 7485, 8976, 10462] [524, 857, 1559, 2182, 2481, 3058, 3508, 3853, 4602, 5230, 5546, 5904, 6625, 7472, 7889, 8978, 9317, 9640, 9961, 10462]
[1542, 3072, 4590, 6057, 7485, 8976, 10462] [377, 693, 841, 1562, 1742, 2183, 2471, 3058, 3833, 4598, 5170, 5548, 5878, 6299, 6590, 7461, 7859, 8983, 9335, 9632, 9971, 10462]
[1542, 3072, 4590, 6057, 7485, 8976, 10462] [1608, 3129, 7526, 7904, 8183, 8525, 10462]
[1542, 3072, 4590, 6057, 7485, 8976, 10462] [1601, 3084, 3554, 4610, 5738, 6136, 7143, 7505, 8212, 8651, 8823, 9021, 10154, 10462]
[1542, 3072, 4590, 6057, 7485, 8976, 10462] [820, 1597, 3082, 3495, 3976, 4619, 5385, 6031, 7501, 8501, 8945, 9800, 10462]
[1542, 3072, 4590, 6057, 7485, 8976, 10462] [350, 911, 1517, 2163, 3071, 3393, 3698, 4058, 4735, 5206, 6027, 7460, 8631, 8966, 9430, 10462]
[1542, 3072, 4590, 6057, 7485, 8976, 10462] [643, 825, 1565, 3079, 3951, 4610, 6053, 7507, 8995, 9797, 10462]
[1542, 3072, 4590, 6057, 7485, 8976, 10462] [439, 684, 844, 1551, 2037, 2474, 3059, 3634, 3832, 4600, 5079, 5397, 5724, 6050, 6507, 7497, 7891, 8991, 9847, 10462]
[1542, 3072, 4590, 6057, 7485, 8976, 10462] [332, 858, 1546, 2180, 2476, 3066, 3814, 4602, 5243, 5536, 5995, 6605, 7470, 7859, 8374, 8984, 9339, 9970, 10462]
[1542, 3072, 4590, 6057, 7485, 8976, 10462] [844, 1551, 1887, 2182, 2470, 3068, 3791, 4590, 5161, 5542, 5718, 5923, 6615, 7360, 7884, 8976, 9322, 9647, 9965, 10462]
[1542, 3072, 4590, 6057, 7485, 8976, 10462] [1599, 3089, 4618, 7508, 9084, 10462]
[1542, 3072, 4590, 6057, 7485, 8976, 10462] [1599, 3095, 4631, 7516, 9055, 10462]
[1542, 3072, 4590, 6057, 7485, 8976, 10462] [476, 646, 835, 1564, 3082, 3885, 4607, 6049, 7507, 8998, 10462]
[1542, 3072, 4590, 6057, 7485, 8976, 10462] [852, 1547, 1869, 2386, 3055, 3714, 4604, 5109, 5440, 6039, 7500, 7862, 8981, 9528, 9833, 10462]
[1565, 2048, 2405, 3078, 3875, 4613, 6055, 7510, 8989, 10462]
[1605 2846 4136 5300]
[1605, 2846, 4136, 5300, 6375]
[1605, 2846, 4136, 5300, 6375] [414, 1628, 2870, 3301, 4162, 4702, 5329, 6375]
[1605, 2846, 4136, 5300, 6375] [297, 1053, 1621, 2441, 2861, 3185, 4159, 4701, 5314, 6375]
[1605, 2846, 4136, 5300, 6375] [291, 1151, 1617, 2862, 3169, 4155, 4699, 5321, 6375]
[1605, 2846, 4136, 5300, 6375] [340, 1612, 2309, 2853, 3188, 4144, 4613, 4702, 5313, 5745, 6003, 6375]
[1605, 2846, 4136, 5300, 6375] [870, 1627, 2166, 2874, 4193, 4870, 5407, 6375]
[1605, 2846, 4136, 5300, 6375] [452, 1014, 1630, 2877, 3266, 3584, 4158, 4794, 5366, 6074, 6375]
[1605, 2846, 4136, 5300, 6375] [419, 874, 1626, 2855, 3275, 4150, 4747, 5367, 6019, 6375]
[1605, 2846, 4136, 5300, 6375] [61, 281, 452, 884, 1631, 1945, 2393, 2845, 3266, 4111, 4715, 4985, 5181, 5327, 6092, 6375]
[1605, 2846, 4136, 5300, 6375] [325, 1619, 2867, 3197, 4163, 4691, 5322, 6375]
[1605, 2846, 4136, 5300, 6375] [259, 1101, 1617, 2855, 3184, 4155, 4688, 5309, 6375]
[1605, 2846, 4136, 5300, 6375] [263, 1106, 1619, 2852, 3176, 3733, 4150, 4702, 5317, 6375]

                    0           1           2            3
F1           0.809650    0.180477    0.400000     1.000000
AUC          0.852137    0.125307    0.625000     1.000000
FP           1.272727    1.202451    0.000000     4.000000
DD         454.422078  874.256752    0.000000  4006.000000
Threshold  100.000000    0.000000  100.000000   100.000000
Covering     0.860011    0.125635    0.521672     1.000000
Runtime     16.296229   10.239380    0.732900    38.045784

[1275 2746 4184]
[1275, 2746, 4184, 5597]
[1319, 2804, 3260, 4307, 5597]
[]
[954]
[262, 954]
[1513 1935]
[1513, 1935, 3423]
[68, 1628, 2011, 3423]
[1429 2844 4098]
[1429, 2844, 4098, 5952]
[1485, 2886, 3290, 4177, 5952]
[]
[6200]
[370, 996, 6200]
[4175 5290 6760 7750]
[4175, 5290, 6760, 7750, 8740]
[229, 361, 917, 4189, 5350, 5925, 6762, 7222, 7770, 8740]
[1525 3070 4320 5690 6930]
[1525, 3070, 4320, 5690, 6930, 8260]
[937, 1546, 3091, 4396, 5729, 6977, 8260]
[1473 2820]
[1473, 2820, 4296]
[105, 912, 1517, 2879, 4296]
[1575 3125]
[1575, 3125, 4504]
[304, 1598, 3152, 4504]
[1290]
[1290, 2860]
[1312, 2860]
[1291 2884 4272 5977]
[1291, 2884, 4272, 5977, 7238]
[285, 1408, 2912, 4309, 6009, 6494, 7238]
[1443 1857]
[1443, 1857, 2781]
[1471, 1909, 2781]
[1611 2979]
[1611, 2979, 4111]
[1628, 3016, 4111]
[]
[1303]
[304, 1303]
[1440 3006 4383 4862 6381]
[1440, 3006, 4383, 4862, 6381, 7948]
[128, 1460, 3023, 4434, 6401, 7948]
[1542 3072 4590 6057 7485 8976]
[1542, 3072, 4590, 6057, 7485, 8976, 10462]
[1568, 2413, 3094, 4617, 6061, 7537, 9012, 10462]
[1605 2846 4136 5300]
[1605, 2846, 4136, 5300, 6375]
[326, 1618, 2863, 3184, 4150, 4703, 5323, 6375]
[2227]
[2227, 3561]
[297, 878, 1268, 2223, 3217, 3561]
[3309]
[3309, 4446]
[3305, 4047, 4446]
[]
[2761]
[375, 888, 2761]
[]
[456]
[456]
[]
[1137]
[324, 1137]
<wrappers.OnlineRuLSIF object at 0x77eee8a5e480>

                    0           1           2            3
F1           0.764838    0.170484    0.500000     1.000000
AUC          0.812013    0.128957    0.583333     1.000000
FP           1.500000    1.300183    0.000000     5.000000
DD         496.623972  800.154949    0.000000  3678.000000
Threshold  100.000000    0.000000  100.000000   100.000000
Covering     0.839439    0.109913    0.545364     1.000000
Runtime     42.929937   25.708809    2.192463    95.742753

CPU times: user 4.19 s, sys: 1.48 s, total: 5.68 s
Wall time: 21min 44s

In [ ]:
%%time

dir_path = "../../datasets/has2023DataR/"


models = [wrappers.OrigRuLSIF(alpha=0.1, kernel_num=10, window_size=250, step=10, periods=1, height=0.1)]


for amodel in models:
    report = run_test_on_dataset(dir_path, amodel, downsample=1, margin=100, verbose=0, sigma=1.0,seed=12345)
    print(amodel)
    for rep in report:
        display(rep)

[1275 2746 4184]
[1275, 2746, 4184, 5597]
[1267, 1737, 2740, 4200, 4757, 5270, 5597]
[]
[954]
[367, 954]
[1513 1935]
[1513, 1935, 3423]
[1530, 3117, 3423]
[1429 2844 4098]
[1429, 2844, 4098, 5952]
[1417, 2817, 4110, 5952]
[]
[6200]
[270, 540, 747, 1280, 1800, 2187, 2587, 3527, 3937, 6200]
[4175 5290 6760 7750]
[4175, 5290, 6760, 7750, 8740]
[270, 877, 4410, 5270, 5717, 6757, 7040, 7197, 7740, 8740]
[1525 3070 4320 5690 6930]
[1525, 3070, 4320, 5690, 6930, 8260]
[840, 1517, 3047, 4340, 5670, 6917, 8260]
[1473 2820]
[1473, 2820, 4296]
[1470, 2827, 3247, 4296]
[1575 3125]
[1575, 3125, 4504]
[320, 1557, 2007, 3107, 4504]
[1290]
[1290, 2860]
[1287, 2860]
[1291 2884 4272 5977]
[1291, 2884, 4272, 5977, 7238]
[317, 590, 910, 1270, 1750, 2877, 4260, 5977, 6490, 7238]
[1443 1857]
[1443, 1857, 2781]
[1437, 1870, 2781]
[1611 2979]
[1611, 2979, 4111]
[1610, 2970, 4111]
[]
[1303]
[467, 830, 980, 1303]
[1440 3006 4383 4862 6381]
[1440, 3006, 4383, 4862, 6381, 7948]
[1420, 2997, 4420, 4600, 4870, 6357, 7948]
[1542 3072 4590 6057 7485 8976]
[1542, 3072, 4590, 6057, 7485, 8976, 10462]
[1547, 1957, 2387, 2637, 3040, 3667, 3887, 4577, 5060, 5327, 5957, 6397, 6987, 7447, 8970, 9810, 10137, 10462]
[1605 2846 4136 5300]
[1605, 2846, 4136, 5300, 6375]
[357, 1580, 2837, 3210, 4130, 4677, 5307, 5877, 6375]
[2227]
[2227, 3561]
[270, 600, 970, 1250, 1810, 2227, 2717, 2887, 3177, 3561]
[3309]
[3309, 4446]
[367, 1030, 1370, 1647, 2710, 3300, 3787, 3960, 4446]
[]
[2761]
[270, 757, 1317, 2290, 2761]
[]
[456]

ValueError: cannot reshape array of size 0 into shape (0,newaxis)

In [15]:
s = "../data/MNIST_SWCPD/sample0.csv"

target = s.split("/")[-1].split(".")[0]+".npy"

s.split("/")[:-1]

['..', 'data', 'MNIST_SWCPD']

# MNIST

In [2]:
%%time

dir_path = "../data/mnist/"

# models = [wrappers.RupturesBinseg(model='rbf', jump=10), 
#           wrappers.RupturesPelt(model='rbf', jump=10), 
#           wrappers.RupturesWindow(model='rbf', jump=10, width=100), 
#           wrappers.OnlineCLF(lag_size=100, height=.1), 
#           wrappers.OnlineRuLSIF(lag_size=100, height=.1), 
#           wrappers.OrigRuLSIF(alpha=0.1, kernel_num=10, window_size=100, step=10, periods=1, height=0.1)]

models = [wrappers.OnlineCLF(lag_size=100, height=.1), 
          wrappers.OnlineRuLSIF(lag_size=100, height=.1),
          wrappers.OrigRuLSIF(alpha=0.1, kernel_num=10, window_size=100, step=10, periods=1, height=0.1)]


for amodel in models:
    report = run_test_on_dataset(dir_path, amodel, downsample=1, margin=20, verbose=0, sigma=5.0)
    print(amodel)
    for rep in report:
        display(rep)

True
True
True
True
True
True
True
True
True
True
<wrappers.OnlineCLF object at 0x7e3395faf110>

                   0         1          2          3
F1          0.666667  0.134687   0.476190   0.857143
AUC         0.668182  0.134993   0.477273   0.859091
FP          4.000000  1.414214   2.000000   6.000000
DD         10.950000  3.479863   5.400000  16.000000
Threshold  10.000000  0.000000  10.000000  10.000000
Covering    0.888061  0.033462   0.839725   0.941963
Runtime     7.640872  3.268985   6.488677  16.942395

                   0         1          2          3
F1          0.771429  0.104810   0.571429   0.952381
AUC         0.773182  0.105048   0.572727   0.954545
FP          2.900000  1.100505   1.000000   5.000000
DD         10.950000  3.479863   5.400000  16.000000
Threshold  20.000000  0.000000  20.000000  20.000000
Covering    0.888061  0.033462   0.839725   0.941963
Runtime     7.640872  3.268985   6.488677  16.942395

                   0         1          2          3
F1          0.857143  0.077762   0.761905   0.952381
AUC         0.859091  0.077938   0.763636   0.954545
FP          2.000000  0.816497   1.000000   3.000000
DD         10.950000  3.479863   5.400000  16.000000
Threshold  30.000000  0.000000  30.000000  30.000000
Covering    0.888061  0.033462   0.839725   0.941963
Runtime     7.640872  3.268985   6.488677  16.942395

                   0         1          2          3
F1          0.895238  0.080312   0.761905   0.952381
AUC         0.897273  0.080494   0.763636   0.954545
FP          1.600000  0.843274   1.000000   3.000000
DD         10.950000  3.479863   5.400000  16.000000
Threshold  40.000000  0.000000  40.000000  40.000000
Covering    0.888061  0.033462   0.839725   0.941963
Runtime     7.640872  3.268985   6.488677  16.942395

                   0         1          2          3
F1          0.933333  0.040156   0.857143   0.952381
AUC         0.935455  0.040247   0.859091   0.954545
FP          1.200000  0.421637   1.000000   2.000000
DD         10.950000  3.479863   5.400000  16.000000
Threshold  50.000000  0.000000  50.000000  50.000000
Covering    0.888061  0.033462   0.839725   0.941963
Runtime     7.640872  3.268985   6.488677  16.942395

True
True
True
True
True
True
True
True
True
True
<wrappers.OnlineRuLSIF object at 0x7e326b5bc3b0>

                   0         1          2          3
F1          0.605195  0.145633   0.272727   0.761905
AUC         0.607121  0.145642   0.275000   0.763636
FP          4.800000  1.751190   3.000000   9.000000
DD         11.503636  3.832362   7.500000  20.636364
Threshold  10.000000  0.000000  10.000000  10.000000
Covering    0.886684  0.029264   0.818179   0.919894
Runtime    17.047756  0.215549  16.734643  17.408990

                   0         1          2          3
F1          0.802165  0.068783   0.727273   0.952381
AUC         0.804924  0.068562   0.733333   0.954545
FP          2.700000  0.823273   1.000000   4.000000
DD         11.503636  3.832362   7.500000  20.636364
Threshold  20.000000  0.000000  20.000000  20.000000
Covering    0.886684  0.029264   0.818179   0.919894
Runtime    17.047756  0.215549  16.734643  17.408990

                   0         1          2          3
F1          0.906061  0.053374   0.818182   0.952381
AUC         0.909167  0.052662   0.825000   0.954545
FP          1.600000  0.699206   1.000000   3.000000
DD         11.503636  3.832362   7.500000  20.636364
Threshold  30.000000  0.000000  30.000000  30.000000
Covering    0.886684  0.029264   0.818179   0.919894
Runtime    17.047756  0.215549  16.734643  17.408990

                   0         1          2          3
F1          0.925108  0.048894   0.818182   0.952381
AUC         0.928258  0.047630   0.825000   0.954545
FP          1.400000  0.699206   1.000000   3.000000
DD         11.503636  3.832362   7.500000  20.636364
Threshold  40.000000  0.000000  40.000000  40.000000
Covering    0.886684  0.029264   0.818179   0.919894
Runtime    17.047756  0.215549  16.734643  17.408990

                   0         1          2          3
F1          0.934199  0.032511   0.857143   0.952381
AUC         0.937424  0.031710   0.859091   0.954545
FP          1.300000  0.483046   1.000000   2.000000
DD         11.503636  3.832362   7.500000  20.636364
Threshold  50.000000  0.000000  50.000000  50.000000
Covering    0.886684  0.029264   0.818179   0.919894
Runtime    17.047756  0.215549  16.734643  17.408990

True
True
True
True
True
True
True
True
True
True
<wrappers.OrigRuLSIF object at 0x7e326b64fcb0>

                   0         1          2          3
F1          0.503578  0.096282   0.333333   0.666667
AUC         0.512599  0.099389   0.337500   0.675000
FP          3.400000  1.173788   2.000000   5.000000
DD          9.957738  3.029291   5.500000  15.375000
Threshold  10.000000  0.000000  10.000000  10.000000
Covering    0.629847  0.072006   0.531934   0.726995
Runtime     0.755754  0.019989   0.742016   0.803356

                   0         1          2          3
F1          0.691572  0.070669   0.588235   0.777778
AUC         0.703254  0.068458   0.607143   0.787500
FP          1.700000  0.674949   1.000000   3.000000
DD          9.957738  3.029291   5.500000  15.375000
Threshold  20.000000  0.000000  20.000000  20.000000
Covering    0.629847  0.072006   0.531934   0.726995
Runtime     0.755754  0.019989   0.742016   0.803356

                   0         1          2          3
F1          0.735501  0.067535   0.588235   0.842105
AUC         0.747758  0.062469   0.607143   0.844444
FP          1.300000  0.483046   1.000000   2.000000
DD          9.957738  3.029291   5.500000  15.375000
Threshold  30.000000  0.000000  30.000000  30.000000
Covering    0.629847  0.072006   0.531934   0.726995
Runtime     0.755754  0.019989   0.742016   0.803356

                   0         1          2          3
F1          0.746027  0.075501   0.588235   0.842105
AUC         0.758313  0.069343   0.607143   0.844444
FP          1.200000  0.421637   1.000000   2.000000
DD          9.957738  3.029291   5.500000  15.375000
Threshold  40.000000  0.000000  40.000000  40.000000
Covering    0.629847  0.072006   0.531934   0.726995
Runtime     0.755754  0.019989   0.742016   0.803356

                   0         1          2          3
F1          0.757792  0.054399   0.705882   0.842105
AUC         0.770456  0.046944   0.728571   0.844444
FP          1.100000  0.316228   1.000000   2.000000
DD          9.957738  3.029291   5.500000  15.375000
Threshold  50.000000  0.000000  50.000000  50.000000
Covering    0.629847  0.072006   0.531934   0.726995
Runtime     0.755754  0.019989   0.742016   0.803356

CPU times: user 2.56 s, sys: 1.02 s, total: 3.58 s
Wall time: 4min 15s

In [13]:
from test_utils import *
from NNCPD_Puchkin24 import *
import time
dir_path = "../data/mnist/"

files = get_files_list(dir_path)
files.sort()


CPS_NN = {}
RT_NN = []
ind_cps = 0
for afile in files:
    
    data = pd.read_csv(afile, index_col=False)
    label = data["Label"].values
    X = data.drop(columns=["Time", "Label"]).values
    X = np.nan_to_num(X)
    T = np.arange(len(X))

    # apply standard scaler
    X = StandardScaler().fit_transform(X)
      
    change_points = list(T[label == 1]) + [len(X)]


        


    # Apply the change point detection procedure
    # with the class of neural networks

    # Initialization
    st_nn = 0
    new_st_nn = 0

    # the threshold
    z_nn = 25

    # Initialization of the test statistic
    S_nn = np.empty(0)

    # Initialization of the list of detected change points
    change_points_nn = []


    # Initialization of the delays array and
    # the false alarms counter
    delays_nn = np.empty(0)
    current_change_point_ind = 0
    false_alarms_nn = 0

    start = time.time()
    while new_st_nn >= 0:
        
        # Run the procedure until the moment
        # it reports a change point occurrence
        new_S_nn, new_st_nn = compute_test_stat_nn(X[st_nn + 1:], z_nn, n_epochs=5)
        
        S_nn = np.append(S_nn, new_S_nn)
        
        st_nn += new_st_nn
        change_points_nn += [int(st_nn)]
        
        if(new_st_nn > 0):
            print('Detected change point (neural networks):', st_nn)
            
        if (st_nn < change_points[current_change_point_ind]):
            false_alarms_nn += 1
        
        else:
            delays_nn = np.append(delays_nn, np.array([st_nn - change_points[current_change_point_ind]]), axis=0)
            current_change_point_ind += 1
    end = time.time()
    print('Neural networks. Number of false alarms:', false_alarms_nn, '; average delay:', np.mean(delays_nn),\
        '±', np.std(delays_nn))
    RT_NN.append(end-start)
    CPS_NN[ind_cps] = change_points_nn
    ind_cps+=1  
    print(change_points)

Detected change point (neural networks): 199
Detected change point (neural networks): 382
Detected change point (neural networks): 559
Detected change point (neural networks): 742
Detected change point (neural networks): 923
Detected change point (neural networks): 1105
Detected change point (neural networks): 1285
Detected change point (neural networks): 1463
Detected change point (neural networks): 1640
Neural networks. Number of false alarms: 1 ; average delay: 21.666666666666668 ± 0.816496580927726
[178, 360, 537, 720, 901, 1083, 1264, 1443, 1617, 1797]
Detected change point (neural networks): 200
Detected change point (neural networks): 384
Detected change point (neural networks): 558
Detected change point (neural networks): 739
Detected change point (neural networks): 922
Detected change point (neural networks): 1107
Detected change point (neural networks): 1286
Detected change point (neural networks): 1465
Detected change point (neural networks): 1641
Neural networks. Number of false alarms: 1 ; average delay: 22.11111111111111 ± 1.5947444549341472
[178, 360, 537, 720, 901, 1083, 1264, 1443, 1617, 1797]
Detected change point (neural networks): 198
Detected change point (neural networks): 383
Detected change point (neural networks): 562
Detected change point (neural networks): 740
Detected change point (neural networks): 923
Detected change point (neural networks): 1104
Detected change point (neural networks): 1284
Detected change point (neural networks): 1463
Detected change point (neural networks): 1639
Neural networks. Number of false alarms: 1 ; average delay: 21.444444444444443 ± 1.640535895581489
[178, 360, 537, 720, 901, 1083, 1264, 1443, 1617, 1797]
Detected change point (neural networks): 200
Detected change point (neural networks): 381
Detected change point (neural networks): 561
Detected change point (neural networks): 740
Detected change point (neural networks): 923
Detected change point (neural networks): 1108
Detected change point (neural networks): 1287
Detected change point (neural networks): 1467
Detected change point (neural networks): 1637
Neural networks. Number of false alarms: 1 ; average delay: 22.333333333333332 ± 1.699673171197595
[178, 360, 537, 720, 901, 1083, 1264, 1443, 1617, 1797]
Detected change point (neural networks): 199
Detected change point (neural networks): 381
Detected change point (neural networks): 559
Detected change point (neural networks): 740
Detected change point (neural networks): 924
Detected change point (neural networks): 1104
Detected change point (neural networks): 1285
Detected change point (neural networks): 1465
Detected change point (neural networks): 1640
Neural networks. Number of false alarms: 1 ; average delay: 21.555555555555557 ± 0.9558139185602919
[178, 360, 537, 720, 901, 1083, 1264, 1443, 1617, 1797]
Detected change point (neural networks): 199
Detected change point (neural networks): 387
Detected change point (neural networks): 559
Detected change point (neural networks): 742
Detected change point (neural networks): 924
Detected change point (neural networks): 1105
Detected change point (neural networks): 1286
Detected change point (neural networks): 1466
Detected change point (neural networks): 1644
Neural networks. Number of false alarms: 1 ; average delay: 23.22222222222222 ± 2.096440251568134
[178, 360, 537, 720, 901, 1083, 1264, 1443, 1617, 1797]
Detected change point (neural networks): 199
Detected change point (neural networks): 384
Detected change point (neural networks): 562
Detected change point (neural networks): 740
Detected change point (neural networks): 923
Detected change point (neural networks): 1105
Detected change point (neural networks): 1284
Detected change point (neural networks): 1466
Detected change point (neural networks): 1638
Neural networks. Number of false alarms: 1 ; average delay: 22.0 ± 1.632993161855452
[178, 360, 537, 720, 901, 1083, 1264, 1443, 1617, 1797]
Detected change point (neural networks): 198
Detected change point (neural networks): 385
Detected change point (neural networks): 561
Detected change point (neural networks): 741
Detected change point (neural networks): 922
Detected change point (neural networks): 1104
Detected change point (neural networks): 1284
Detected change point (neural networks): 1464
Detected change point (neural networks): 1643
Neural networks. Number of false alarms: 1 ; average delay: 22.11111111111111 ± 2.1314806770278754
[178, 360, 537, 720, 901, 1083, 1264, 1443, 1617, 1797]
Detected change point (neural networks): 201
Detected change point (neural networks): 381
Detected change point (neural networks): 559
Detected change point (neural networks): 741
Detected change point (neural networks): 921
Detected change point (neural networks): 1105
Detected change point (neural networks): 1286
Detected change point (neural networks): 1465
Detected change point (neural networks): 1640
Neural networks. Number of false alarms: 1 ; average delay: 21.77777777777778 ± 0.9162456945817022
[178, 360, 537, 720, 901, 1083, 1264, 1443, 1617, 1797]
Detected change point (neural networks): 199
Detected change point (neural networks): 382
Detected change point (neural networks): 559
Detected change point (neural networks): 743
Detected change point (neural networks): 923
Detected change point (neural networks): 1107
Detected change point (neural networks): 1286
Detected change point (neural networks): 1463
Detected change point (neural networks): 1641
Neural networks. Number of false alarms: 1 ; average delay: 22.22222222222222 ± 1.227262335243029
[178, 360, 537, 720, 901, 1083, 1264, 1443, 1617, 1797]

In [20]:
from SWCPD import BaseDetector as SWDCP
from test_utils import *
import time
from sklearn.preprocessing import MinMaxScaler

In [22]:
CPS_NN

{0: [199, 382, 559, 742, 923, 1105, 1285, 1463, 1640, 1639],
 1: [200, 384, 558, 739, 922, 1107, 1286, 1465, 1641, 1640],
 2: [198, 383, 562, 740, 923, 1104, 1284, 1463, 1639, 1638],
 3: [200, 381, 561, 740, 923, 1108, 1287, 1467, 1637, 1636],
 4: [199, 381, 559, 740, 924, 1104, 1285, 1465, 1640, 1639],
 5: [199, 387, 559, 742, 924, 1105, 1286, 1466, 1644, 1643],
 6: [199, 384, 562, 740, 923, 1105, 1284, 1466, 1638, 1637],
 7: [198, 385, 561, 741, 922, 1104, 1284, 1464, 1643, 1642],
 8: [201, 381, 559, 741, 921, 1105, 1286, 1465, 1640, 1639],
 9: [199, 382, 559, 743, 923, 1107, 1286, 1463, 1641, 1640]}

In [41]:
RT_NN

[286.545711517334,
 285.43733310699463,
 284.4674618244171,
 283.05568861961365,
 284.5523386001587,
 285.2369034290314,
 284.5166492462158,
 283.97826313972473,
 283.68565368652344,
 281.702748298645]

In [27]:
detector = SWDCP(data=X.astype(np.float32),window_length=100,max_history=100,significance=0.075,use_cuda=False)

keys = ['AUC','FP','COV','DD']



METRICS_NN = {m: { k: [] for k in keys }  for m in [10,20,30,50]}

GT = [178, 360, 537, 720, 901, 1083, 1264, 1443, 1617]
for k,cps in CPS_NN.items():
    detector.change_points['loc'] = cps

    for m in [10,20,30,50]:
        f1, cov, auc_score, fp, delay = detector.evaluate(GT,m)
        METRICS_NN[m]['AUC'].append(auc_score)
        METRICS_NN[m]['COV'].append(cov)
        METRICS_NN[m]['FP'].append(fp)
        METRICS_NN[m]['DD'].append(delay[1])

for k in METRICS_NN.keys():
    print(k)
    print(f"Mean AUC {np.mean((METRICS_NN[k]['AUC']))} +- {np.std((METRICS_NN[k]['AUC']))}")
    print(f"Mean Cov {np.mean((METRICS_NN[k]['COV']))} +- {np.std((METRICS_NN[k]['COV']))}")
    print(f"Mean FP {np.mean((METRICS_NN[k]['FP']))} +- {np.min((METRICS_NN[k]['FP'])),np.max((METRICS_NN[k]['FP']))}")
    print(f"Mean FP {np.mean((METRICS_NN[k]['DD']))} +- {np.min((METRICS_NN[k]['DD'])),np.max((METRICS_NN[k]['DD']))}")

10
Mean AUC 0.09545454545454546 +- 0.0
Mean Cov 0.8023735259926532 +- 0.003887795357850402
Mean FP 10.0 +- (10, 10)
Mean FP 22.070000000000004 +- (21.4, 23.5)
20
Mean AUC 0.2481818181818182 +- 0.10629368329039134
Mean Cov 0.8023735259926532 +- 0.003887795357850402
Mean FP 8.3 +- (6, 10)
Mean FP 22.070000000000004 +- (21.4, 23.5)
30
Mean AUC 0.9545454545454547 +- 1.1102230246251565e-16
Mean Cov 0.8023735259926532 +- 0.003887795357850402
Mean FP 0.0 +- (0, 0)
Mean FP 22.070000000000004 +- (21.4, 23.5)
50
Mean AUC 0.9545454545454547 +- 1.1102230246251565e-16
Mean Cov 0.8023735259926532 +- 0.003887795357850402
Mean FP 0.0 +- (0, 0)
Mean FP 22.070000000000004 +- (21.4, 23.5)

In [28]:
dir_path = "../data/mnist/"


files = get_files_list(dir_path)
files.sort()

keys = ['AUC','FP','COV','DD']



METRICS = {m: { k: [] for k in keys }  for m in [10,20,30,50]}

print(METRICS)

RT = []

for afile in files:
    data = pd.read_csv(afile, index_col=False)

        # decompose data
    label = data["Label"].values
    X = data.drop(columns=["Time", "Label"]).values
    X = np.nan_to_num(X)
    #X = MinMaxScaler().fit_transform(X)
    T = np.arange(len(X))
    y_true = list(T[label == 1]) + [len(X)]
    print(y_true)

    detector = SWDCP(data=X.astype(np.float32),window_length=100,max_history=100,significance=0.075,use_cuda=False)
    start = time.time()
    detector.process_dataloader(p=2,n_theta=1000,seed=2025,verbose=False)
    end = time.time()
    RT.append(end-start)
    for m in [10,20,30,50]:
        f1, cov, auc_score, fp, delay = detector.evaluate(y_true[:-1],m)
        METRICS[m]['AUC'].append(auc_score)
        METRICS[m]['COV'].append(cov)
        METRICS[m]['FP'].append(fp)
        METRICS[m]['DD'].append(delay[1])

{10: {'AUC': [], 'FP': [], 'COV': [], 'DD': []}, 20: {'AUC': [], 'FP': [], 'COV': [], 'DD': []}, 30: {'AUC': [], 'FP': [], 'COV': [], 'DD': []}, 50: {'AUC': [], 'FP': [], 'COV': [], 'DD': []}}
[178, 360, 537, 720, 901, 1083, 1264, 1443, 1617, 1797]

100%|██████████| 1698/1698 [00:04<00:00, 388.52it/s]

[178, 360, 537, 720, 901, 1083, 1264, 1443, 1617, 1797]

100%|██████████| 1698/1698 [00:04<00:00, 390.36it/s]

[178, 360, 537, 720, 901, 1083, 1264, 1443, 1617, 1797]

100%|██████████| 1698/1698 [00:04<00:00, 405.76it/s]

[178, 360, 537, 720, 901, 1083, 1264, 1443, 1617, 1797]

100%|██████████| 1698/1698 [00:04<00:00, 401.09it/s]

[178, 360, 537, 720, 901, 1083, 1264, 1443, 1617, 1797]

100%|██████████| 1698/1698 [00:04<00:00, 394.02it/s]

[178, 360, 537, 720, 901, 1083, 1264, 1443, 1617, 1797]

100%|██████████| 1698/1698 [00:04<00:00, 399.97it/s]

[178, 360, 537, 720, 901, 1083, 1264, 1443, 1617, 1797]

100%|██████████| 1698/1698 [00:04<00:00, 416.87it/s]

[178, 360, 537, 720, 901, 1083, 1264, 1443, 1617, 1797]

100%|██████████| 1698/1698 [00:04<00:00, 408.06it/s]

[178, 360, 537, 720, 901, 1083, 1264, 1443, 1617, 1797]

100%|██████████| 1698/1698 [00:04<00:00, 406.52it/s]

[178, 360, 537, 720, 901, 1083, 1264, 1443, 1617, 1797]

100%|██████████| 1698/1698 [00:04<00:00, 403.17it/s]

In [37]:
np.mean(RT) ,np.std(RT)

(4.251901030540466, 0.1082743949244289)

In [29]:
for k in METRICS.keys():
    print(k)
    print(f"Mean AUC {np.mean((METRICS[k]['AUC']))} +- {np.std((METRICS[k]['AUC']))}")
    print(f"Mean Cov {np.mean((METRICS[k]['COV']))} +- {np.std((METRICS[k]['COV']))}")
    print(f"Mean FP {np.mean((METRICS[k]['FP']))} +- {np.min((METRICS[k]['FP'])),np.max((METRICS[k]['FP']))}")
    print(f"Mean FP {np.mean((METRICS[k]['DD']))} +- {np.min((METRICS[k]['DD'])),np.max((METRICS[k]['DD']))}")

10
Mean AUC 0.5122727272727272 +- 0.08234803183505623
Mean Cov 0.8960204422907649 +- 0.006585727638095648
Mean FP 5.1 +- (4, 6)
Mean FP 11.101111111111113 +- (9.333333333333334, 12.444444444444445)
20
Mean AUC 0.9663636363636364 +- 0.03858017304349625
Mean Cov 0.8960204422907649 +- 0.006585727638095648
Mean FP 0.2 +- (0, 1)
Mean FP 11.101111111111113 +- (9.333333333333334, 12.444444444444445)
30
Mean AUC 0.9863636363636363 +- 0.020829889522526526
Mean Cov 0.8960204422907649 +- 0.006585727638095648
Mean FP 0.0 +- (0, 0)
Mean FP 11.101111111111113 +- (9.333333333333334, 12.444444444444445)
50
Mean AUC 0.9863636363636363 +- 0.020829889522526526
Mean Cov 0.8960204422907649 +- 0.006585727638095648
Mean FP 0.0 +- (0, 0)
Mean FP 11.101111111111113 +- (9.333333333333334, 12.444444444444445)

|Method|AUC||FP||||
|---|---|---|---|---|---|---|
||$\tau=20$| $\tau=30$|$\tau=20$|$\tau=30$| **Cov**|**DD**|
|SWCDP|$0.97 \pm 0.04$|$0.99 \pm 0.02$|$0.2$ (0;1)|$0.0$ (0;0)|$0.90 \pm 0.01$|$11.1$ (9.3;12.4)|
|DeepClf [1]|$0.86 \pm 0.09$|$0.96 \pm 0.08$|$1.5$ (0;3)|$0.9$ (0;2)|$0.89 \pm 0.02$|$10.7$ (5.6;17)|
|DeepRulif [1]|$0.80 \pm 0.09$|$0.90 \pm 0.05$|$2.2$ (0;4)|$1.2$ (0;3)|$0.88 \pm 0.02$|$12.1$ (7.1;18)|
|DeepNN [2]|$0.24 \pm 0.11$|$0.96 \pm 0.01$|$8.3$ (6;10)|$0.0$ (0;0)|$0.80 \pm 0.02$|$22.1$ (21.4;23.5)|
|Rulif [3]|$0.72 \pm 0.09$|$0.84 \pm 0.1$|$1.6$ (0;3)|$0.4$ (0;1)|$0.66 \pm 0.02$|$11.5$ (6.8;14.3)|

# SUSY

In [10]:
%%time

dir_path = "../data/susy/"

models = [wrappers.RupturesBinseg(model='rbf', jump=10), 
          wrappers.RupturesPelt(model='rbf', jump=10), 
          wrappers.RupturesWindow(model='rbf', jump=10, width=100), 
          wrappers.OnlineCLF(lag_size=100, height=.1), 
          wrappers.OnlineRuLSIF(lag_size=100, height=.1), 
          wrappers.OrigRuLSIF(alpha=0.1, kernel_num=10, window_size=100, step=10, periods=1, height=0.1)]

for amodel in models:
    report = run_test_on_dataset(dir_path, amodel, downsample=10, margin=50, verbose=0, sigma=2)
    print(amodel)
    display(report)

<wrappers.RupturesBinseg object at 0x7f85ec03d3a0>

           0         1
RI  0.983040  0.006288
F1  0.897502  0.098246

<wrappers.RupturesPelt object at 0x7f85ec03d3d0>

           0         1
RI  0.983205  0.005641
F1  0.919298  0.078012

<wrappers.RupturesWindow object at 0x7f85ec03d940>

           0         1
RI  0.973265  0.011171
F1  0.833694  0.102336

<wrappers.OnlineCLF object at 0x7f85ec03d9d0>

           0         1
RI  0.983744  0.004759
F1  0.989473  0.022191

<wrappers.OnlineRuLSIF object at 0x7f85ec03d4c0>

           0         1
RI  0.976334  0.004885
F1  0.966666  0.053672

<wrappers.OrigRuLSIF object at 0x7f85ec03d4f0>

           0         1
RI  0.954352  0.017995
F1  0.762416  0.139424

CPU times: user 16.2 s, sys: 2.49 s, total: 18.6 s
Wall time: 17min 41s

# HTRU2

In [11]:
%%time

dir_path = "../data/htru2/"

models = [wrappers.RupturesBinseg(model='rbf', jump=10), 
          wrappers.RupturesPelt(model='rbf', jump=10), 
          wrappers.RupturesWindow(model='rbf', jump=10, width=100), 
          wrappers.OnlineCLF(lag_size=100, height=.1), 
          wrappers.OnlineRuLSIF(lag_size=100, height=.1), 
          wrappers.OrigRuLSIF(alpha=0.1, kernel_num=10, window_size=100, step=10, periods=1, height=0.1)]

for amodel in models:
    report = run_test_on_dataset(dir_path, amodel, downsample=10, margin=50, verbose=0, sigma=5)
    print(amodel)
    display(report)

<wrappers.RupturesBinseg object at 0x7f85ec2375b0>

           0         1
RI  0.984690  0.011205
F1  0.905222  0.114781

<wrappers.RupturesPelt object at 0x7f85ec237490>

           0         1
RI  0.981880  0.010415
F1  0.893715  0.102571

<wrappers.RupturesWindow object at 0x7f85ec237040>

           0         1
RI  0.967245  0.008168
F1  0.818190  0.091582

<wrappers.OnlineCLF object at 0x7f85ec237400>

           0         1
RI  0.981505  0.005325
F1  0.978362  0.038303

<wrappers.OnlineRuLSIF object at 0x7f85ec237f10>

           0         1
RI  0.973949  0.006867
F1  0.934444  0.056522

<wrappers.OrigRuLSIF object at 0x7f85ec2374f0>

           0         1
RI  0.959620  0.009531
F1  0.849756  0.084128

CPU times: user 13.4 s, sys: 2.45 s, total: 15.9 s
Wall time: 17min 18s

# MAGIC

In [12]:
%%time

dir_path = "../data/magic/"

models = [wrappers.RupturesBinseg(model='rbf', jump=10), 
          wrappers.RupturesPelt(model='rbf', jump=10), 
          wrappers.RupturesWindow(model='rbf', jump=10, width=100), 
          wrappers.OnlineCLF(lag_size=100, height=.1), 
          wrappers.OnlineRuLSIF(lag_size=100, height=.1), 
          wrappers.OrigRuLSIF(alpha=0.1, kernel_num=10, window_size=100, step=10, periods=1, height=0.1)]

for amodel in models:
    report = run_test_on_dataset(dir_path, amodel, downsample=10, margin=50, verbose=0, sigma=2)
    print(amodel)
    display(report)

<wrappers.RupturesBinseg object at 0x7f85ec237cd0>

           0         1
RI  0.964965  0.013177
F1  0.677122  0.190681

<wrappers.RupturesPelt object at 0x7f85ec237ac0>

           0         1
RI  0.971185  0.016209
F1  0.831365  0.096374

<wrappers.RupturesWindow object at 0x7f85ec152640>

           0         1
RI  0.965390  0.008697
F1  0.769203  0.085897

<wrappers.OnlineCLF object at 0x7f85ec152d60>

           0         1
RI  0.963498  0.008331
F1  0.882078  0.077420

<wrappers.OnlineRuLSIF object at 0x7f85ec152d90>

           0         1
RI  0.966791  0.012904
F1  0.869556  0.137267

<wrappers.OrigRuLSIF object at 0x7f85ec152460>

           0         1
RI  0.850414  0.094979
F1  0.584186  0.166599

CPU times: user 13.8 s, sys: 2.3 s, total: 16.1 s
Wall time: 17min 40s

# Higgs

In [13]:
%%time

dir_path = "../data/higgs/"

models = [wrappers.RupturesBinseg(model='rbf', jump=10), 
          wrappers.RupturesPelt(model='rbf', jump=10), 
          wrappers.RupturesWindow(model='rbf', jump=10, width=200), 
          wrappers.OnlineCLF(lag_size=200, height=.1), 
          wrappers.OnlineRuLSIF(lag_size=200, height=.1), 
          wrappers.OrigRuLSIF(alpha=0.1, kernel_num=10, window_size=100, step=10, periods=1, height=0.1)]

for amodel in models:
    report = run_test_on_dataset(dir_path, amodel, downsample=5, margin=50, verbose=0)
    print(amodel)
    display(report)

<wrappers.RupturesBinseg object at 0x7f85ec1f1610>

           0         1
RI  0.959744  0.017775
F1  0.513627  0.167930

<wrappers.RupturesPelt object at 0x7f85ec1f1820>

           0         1
RI  0.908315  0.010563
F1  0.175431  0.260583

<wrappers.RupturesWindow object at 0x7f85ec1f12e0>

           0         1
RI  0.954359  0.008388
F1  0.523818  0.141527

<wrappers.OnlineCLF object at 0x7f85ec1f1790>

           0         1
RI  0.971241  0.011186
F1  0.757237  0.159999

<wrappers.OnlineRuLSIF object at 0x7f85ec1f13d0>

           0         1
RI  0.974457  0.005138
F1  0.761871  0.105362

<wrappers.OrigRuLSIF object at 0x7f85ec1f10d0>

           0         1
RI  0.747915  0.233792
F1  0.232490  0.207845

CPU times: user 42.6 s, sys: 11.5 s, total: 54.1 s
Wall time: 1h 32min 59s

# EMG

In [14]:
%%time

dir_path = "../data/EMG_Physical_Action_Data_Set/"

models = [wrappers.RupturesBinseg(model='rbf', jump=10), 
          wrappers.RupturesPelt(model='rbf', jump=10), 
          wrappers.RupturesWindow(model='rbf', jump=10, width=100), 
          wrappers.OnlineCLF(lag_size=100, height=.1), 
          wrappers.OnlineRuLSIF(lag_size=100, height=.1), 
          wrappers.OrigRuLSIF(alpha=0.1, kernel_num=10, window_size=100, step=10, periods=1, height=0.1)]

for amodel in models:
    report = run_test_on_dataset(dir_path, amodel, downsample=50, margin=50, verbose=0)
    print(amodel)
    display(report)

<wrappers.RupturesBinseg object at 0x7f85e7693340>

           0         1
RI  0.969000  0.012791
F1  0.898488  0.029202

<wrappers.RupturesPelt object at 0x7f85e7693fa0>

           0         1
RI  0.966179  0.010723
F1  0.886792  0.041223

<wrappers.RupturesWindow object at 0x7f85e7693e20>

           0         1
RI  0.974369  0.012075
F1  0.818434  0.107471

<wrappers.OnlineCLF object at 0x7f85e7693970>

           0         1
RI  0.979054  0.009605
F1  0.972222  0.055556

<wrappers.OnlineRuLSIF object at 0x7f85e7693c10>

           0         1
RI  0.980058  0.004711
F1  0.973684  0.030387

<wrappers.OrigRuLSIF object at 0x7f85e7693730>

           0         1
RI  0.972983  0.018324
F1  0.954044  0.059547

CPU times: user 6.36 s, sys: 1.13 s, total: 7.49 s
Wall time: 5min 29s

# WISDM

In [15]:
%%time

dir_path = "../data/wisdm/"

models = [wrappers.RupturesBinseg(model='rbf', jump=10), 
          wrappers.RupturesPelt(model='rbf', jump=10), 
          wrappers.RupturesWindow(model='rbf', jump=10, width=100), 
          wrappers.OnlineCLF(lag_size=100, height=.1), 
          wrappers.OnlineRuLSIF(lag_size=100, height=.1), 
          wrappers.OrigRuLSIF(alpha=0.1, kernel_num=10, window_size=100, step=10, periods=1, height=0.1)]

for amodel in models:
    report = run_test_on_dataset(dir_path, amodel, downsample=20, margin=50, verbose=0)
    print(amodel)
    display(report)

<wrappers.RupturesBinseg object at 0x7f85ec029b80>

           0         1
RI  0.990174  0.005106
F1  0.882233  0.118083

<wrappers.RupturesPelt object at 0x7f85ec029760>

           0         1
RI  0.989973  0.005085
F1  0.864918  0.122434

<wrappers.RupturesWindow object at 0x7f85ec029640>

           0         1
RI  0.990585  0.004573
F1  0.935753  0.061937

<wrappers.OnlineCLF object at 0x7f85ec0297f0>

           0         1
RI  0.989948  0.004591
F1  0.958640  0.057770

<wrappers.OnlineRuLSIF object at 0x7f85ec07b400>

          0         1
RI  0.98939  0.005578
F1  0.97344  0.040312

<wrappers.OrigRuLSIF object at 0x7f85ec07b1c0>

           0         1
RI  0.988019  0.003424
F1  0.940910  0.064357

CPU times: user 25.9 s, sys: 6.09 s, total: 31.9 s
Wall time: 24min 8s

# Kepler

In [16]:
%%time

dir_path = "../data/kepler/"

models = [wrappers.RupturesBinseg(model='rbf', jump=10), 
          wrappers.RupturesPelt(model='rbf', jump=10), 
          wrappers.RupturesWindow(model='rbf', jump=10, width=20), 
          wrappers.OnlineCLF(lag_size=20, height=1.1), 
          wrappers.OnlineRuLSIF(lag_size=20, height=1.1), 
          wrappers.OrigRuLSIF(alpha=0.1, kernel_num=10, window_size=20, step=10, periods=1, height=1.1)]

for amodel in models:
    report = run_test_on_dataset(dir_path, amodel, downsample=5, margin=20, verbose=0)
    print(amodel)
    display(report)

<wrappers.RupturesBinseg object at 0x7f85e7693dc0>

           0         1
RI  0.949039  0.023165
F1  0.596422  0.062363

<wrappers.RupturesPelt object at 0x7f85e7693190>

           0         1
RI  0.990544  0.012027
F1  0.965490  0.043845

<wrappers.RupturesWindow object at 0x7f85e76938b0>

           0         1
RI  0.985066  0.009546
F1  0.881030  0.047975

<wrappers.OnlineCLF object at 0x7f85e7693790>

           0         1
RI  0.997287  0.001685
F1  0.996621  0.009555

<wrappers.OnlineRuLSIF object at 0x7f85e7693610>

           0         1
RI  0.997307  0.002037
F1  0.971590  0.080353

<wrappers.OrigRuLSIF object at 0x7f85e7693ac0>

           0         1
RI  0.889837  0.031741
F1  0.136065  0.041847

CPU times: user 1min 42s, sys: 29.9 s, total: 2min 12s
Wall time: 1h 26min 13s